import { Category } from './types';

export const APP_VERSION = "1.1.20";

export const CATEGORIES: Category[] = [
  {
    id: 'homework-group',
    name: 'Homework (作業)',
    description: 'Practice units for characters from your class worksheets.',
    icon: '📝',
    isSpecial: true,
    characters: [],
    sequences: [
      {
        id: 'ws-1',
        name: 'Worksheet 1',
        characters: [
          { char: '吃', pinyin: 'chī', zhuyin: 'ㄔ', meaning: 'to eat', difficulty: 2, components: ['口', '乞'] },
          { char: '愛', pinyin: 'ài', zhuyin: 'ㄞˋ', meaning: 'love', difficulty: 3, components: ['爫', '冖', '心', '夂'] },
          { char: '友', pinyin: 'yǒu', zhuyin: 'ㄧㄡˇ', meaning: 'friend (part of 朋友)', difficulty: 2, components: ['ナ', '又'] },
          { char: '朋', pinyin: 'péng', zhuyin: 'ㄆㄥˊ', meaning: 'friend (part of 朋友)', difficulty: 2, components: ['月', '月'] },
          { char: '家', pinyin: 'jiā', zhuyin: 'ㄐㄧㄚ', meaning: 'home / family', difficulty: 2, components: ['宀', '豕'] },
          { char: '大', pinyin: 'dà', zhuyin: 'ㄉㄚˋ', meaning: 'big / great', difficulty: 1, components: ['一', '人'] },
          { char: '氣', pinyin: 'qì', zhuyin: 'ㄑㄧˋ', meaning: 'air / gas / energy', difficulty: 3, components: ['气', '米'] },
          { char: '客', pinyin: 'kè', zhuyin: 'ㄎㄜˋ', meaning: 'guest / customer', difficulty: 3, components: ['宀', '各'] },
          { char: '謝', pinyin: 'xiè', zhuyin: 'ㄒㄧㄝˋ', meaning: 'to thank', difficulty: 4, components: ['言', '身', '寸'] },
          { char: '喝', pinyin: 'hē', zhuyin: 'ㄏㄜ', meaning: 'to drink', difficulty: 3, components: ['口', '曷'] },
          { char: '果', pinyin: 'guǒ', zhuyin: 'ㄍㄨㄛˇ', meaning: 'fruit / result', difficulty: 2, components: ['田', '木'] },
          { char: '水', pinyin: 'shuǐ', zhuyin: 'ㄕㄨㄟˇ', meaning: 'water', difficulty: 1, components: ['水'] },
          { char: '珠', pinyin: 'zhū', zhuyin: 'ㄓㄨ', meaning: 'pearl / bead', difficulty: 3, components: ['王', '朱'] },
          { char: '珍', pinyin: 'zhēn', zhuyin: 'ㄓㄣ', meaning: 'precious / rare', difficulty: 3, components: ['王', '㐱'] },
          { char: '紹', pinyin: 'shào', zhuyin: 'ㄕㄠˋ', meaning: 'to introduce (part of 介紹)', difficulty: 3, components: ['糹', '召'] },
          { char: '介', pinyin: 'jiè', zhuyin: 'ㄐㄧㄝˋ', meaning: 'between (part of 介紹)', difficulty: 2, components: ['人', '丨', '丨'] },
          { char: '我', pinyin: 'wǒ', zhuyin: 'ㄨㄛˇ', meaning: 'I / me', difficulty: 3, components: ['手', '戈'] },
          { char: '自', pinyin: 'zì', zhuyin: 'ㄗˋ', meaning: 'self / from', difficulty: 2, components: ['自'] },
          { char: '茶', pinyin: 'chá', zhuyin: 'ㄔㄚˊ', meaning: 'tea', difficulty: 3, components: ['艹', '人', '木'] },
          { char: '奶', pinyin: 'nǎi', zhuyin: 'ㄋㄞˇ', meaning: 'milk / grandmother', difficulty: 2, components: ['女', '乃'] },
        ]
      },
      {
        id: 'ws-2',
        name: 'Worksheet 2',
        characters: [
          { char: '呢', pinyin: 'ne', zhuyin: 'ㄋㄜ˙', meaning: 'modal particle', difficulty: 2, components: ['口', '尼'] },
          { char: '姓', pinyin: 'xìng', zhuyin: 'ㄒㄧㄥˋ', meaning: 'surname', difficulty: 2, components: ['女', '生'] },
          { char: '字', pinyin: 'zì', zhuyin: 'ㄗˋ', meaning: 'character', difficulty: 2, components: ['宀', '子'] },
          { char: '名', pinyin: 'míng', zhuyin: 'ㄇㄧㄥˊ', meaning: 'name', difficulty: 2, components: ['夕', '口'] },
          { char: '麼', pinyin: 'me', zhuyin: 'ㄇㄜ˙', meaning: 'suffix', difficulty: 2, components: ['麻', '幺'] },
          { char: '什', pinyin: 'shén', zhuyin: 'ㄕㄣˊ', meaning: 'what', difficulty: 1, components: ['亻', '十'] },
          { char: '好', pinyin: 'hǎo', zhuyin: 'ㄏㄠˇ', meaning: 'good / well', difficulty: 1, components: ['女', '子'] },
          { char: '妳', pinyin: 'nǐ', zhuyin: 'ㄋㄧˇ', meaning: 'you (female)', difficulty: 2, components: ['女', '尔'] },
          { char: '歡', pinyin: 'huān', zhuyin: 'ㄏㄨㄢ', meaning: 'joyous / like', difficulty: 4, components: ['欠', '雚'] },
          { char: '喜', pinyin: 'xǐ', zhuyin: 'ㄒㄧˇ', meaning: 'to like / happy', difficulty: 3, components: ['壴', '口'] },
          { char: '尼', pinyin: 'ní', zhuyin: 'ㄋㄧˊ', meaning: 'nun / phonetic', difficulty: 2, components: ['尸', '匕'] },
          { char: '印', pinyin: 'yìn', zhuyin: 'ㄧㄣˋ', meaning: 'print / stamp', difficulty: 3, components: ['卩', '𠂇'] },
          { char: '媽', pinyin: 'mā', zhuyin: 'ㄇㄚ', meaning: 'mother', difficulty: 2, components: ['女', '馬'] },
          { char: '爸', pinyin: 'bà', zhuyin: 'ㄅㄚˋ', meaning: 'father', difficulty: 2, components: ['父', '巴'] },
          { char: '愛', pinyin: 'ài', zhuyin: 'ㄞˋ', meaning: 'love', difficulty: 3, components: ['爫', '冖', '心', '夂'] },
          { char: '問', pinyin: 'wèn', zhuyin: 'ㄨㄣˋ', meaning: 'to ask', difficulty: 3, components: ['門', '口'] },
          { char: '請', pinyin: 'qǐng', zhuyin: 'ㄑㄧㄥˇ', meaning: 'please', difficulty: 3, components: ['言', '青'] },
        ]
      },
      {
        id: 'ws-3',
        name: 'Worksheet 3',
        characters: [
          { char: '謝', pinyin: 'xiè', zhuyin: 'ㄒㄧㄝˋ', meaning: 'to thank', difficulty: 4, components: ['言', '身', '寸'] },
          { char: '大', pinyin: 'dà', zhuyin: 'ㄉㄚˋ', meaning: 'big / great', difficulty: 1, components: ['一', '人'] },
          { char: '家', pinyin: 'jiā', zhuyin: 'ㄐㄧㄚ', meaning: 'home / family', difficulty: 2, components: ['宀', '豕'] },
          { char: '朋', pinyin: 'péng', zhuyin: 'ㄆㄥˊ', meaning: 'friend (part of 朋友)', difficulty: 2, components: ['月', '月'] },
          { char: '友', pinyin: 'yǒu', zhuyin: 'ㄧㄡˇ', meaning: 'friend (part of 朋友)', difficulty: 2, components: ['ナ', '又'] },
          { char: '愛', pinyin: 'ài', zhuyin: 'ㄞˋ', meaning: 'love', difficulty: 3, components: ['爫', '冖', '心', '夂'] },
          { char: '吃', pinyin: 'chī', zhuyin: 'ㄔ', meaning: 'to eat', difficulty: 2, components: ['口', '乞'] },
          { char: '水', pinyin: 'shuǐ', zhuyin: 'ㄕㄨㄟˇ', meaning: 'water', difficulty: 1, components: ['水'] },
          { char: '果', pinyin: 'guǒ', zhuyin: 'ㄍㄨㄛˇ', meaning: 'fruit / result', difficulty: 2, components: ['田', '木'] },
          { char: '喝', pinyin: 'hē', zhuyin: 'ㄏㄜ', meaning: 'to drink', difficulty: 3, components: ['口', '曷'] },
          { char: '客', pinyin: 'kè', zhuyin: 'ㄎㄜˋ', meaning: 'guest / customer', difficulty: 3, components: ['宀', '各'] },
          { char: '氣', pinyin: 'qì', zhuyin: 'ㄑㄧˋ', meaning: 'air / gas / energy', difficulty: 3, components: ['气', '米'] },
          { char: '自', pinyin: 'zì', zhuyin: 'ㄗˋ', meaning: 'self / from', difficulty: 2, components: ['自'] },
          { char: '我', pinyin: 'wǒ', zhuyin: 'ㄨㄛˇ', meaning: 'I / me', difficulty: 3, components: ['手', '戈'] },
          { char: '介', pinyin: 'jiè', zhuyin: 'ㄐㄧㄝˋ', meaning: 'between (part of 介紹)', difficulty: 2, components: ['人', '丨', '丨'] },
          { char: '紹', pinyin: 'shào', zhuyin: 'ㄕㄠˋ', meaning: 'to introduce (part of 介紹)', difficulty: 3, components: ['糹', '召'] },
          { char: '珍', pinyin: 'zhēn', zhuyin: 'ㄓㄣ', meaning: 'precious / rare', difficulty: 3, components: ['王', '㐱'] },
          { char: '珠', pinyin: 'zhū', zhuyin: 'ㄓㄨ', meaning: 'pearl / bead', difficulty: 3, components: ['王', '朱'] },
          { char: '奶', pinyin: 'nǎi', zhuyin: 'ㄋㄞˇ', meaning: 'milk / grandmother', difficulty: 2, components: ['女', '乃'] },
          { char: '茶', pinyin: 'chá', zhuyin: 'ㄔㄚˊ', meaning: 'tea', difficulty: 3, components: ['艹', '人', '木'] },
        ]
      },
      {
        id: 'ws-4',
        name: 'Worksheet 4',
        characters: [
          // Page 1
          { char: '去', pinyin: 'qù', zhuyin: 'ㄑㄩˋ', meaning: 'to go', difficulty: 2, components: ['土', '厶'] },
          { char: '在', pinyin: 'zài', zhuyin: 'ㄗㄞˋ', meaning: 'at / in / to be', difficulty: 2, components: ['才', '土'] },
          { char: '現', pinyin: 'xiàn', zhuyin: 'ㄒㄧㄢˋ', meaning: 'now / present', difficulty: 3, components: ['王', '見'] },
          { char: '鐘', pinyin: 'zhōng', zhuyin: 'ㄓㄨㄥ', meaning: 'clock / bell', difficulty: 4, components: ['金', '中'] },
          { char: '點', pinyin: 'diǎn', zhuyin: 'ㄉㄧㄢˇ', meaning: 'o\'clock / point', difficulty: 3, components: ['黑', '占'] },
          { char: '幾', pinyin: 'jǐ', zhuyin: 'ㄐㄧˇ', meaning: 'how many / which', difficulty: 3, components: ['幺', '幺', '戍'] },
          // Page 2
          { char: '子', pinyin: 'zǐ', zhuyin: 'ㄗˇ', meaning: 'child / suffix', difficulty: 1, components: ['子'] },
          { char: '孩', pinyin: 'hái', zhuyin: 'ㄏㄞˊ', meaning: 'child', difficulty: 3, components: ['子', '亥'] },
          { char: '爸', pinyin: 'bà', zhuyin: 'ㄅㄚˋ', meaning: 'father', difficulty: 2, components: ['父', '巴'] },
          { char: '媽', pinyin: 'mā', zhuyin: 'ㄇㄚ', meaning: 'mother', difficulty: 2, components: ['女', '馬'] },
          { char: '校', pinyin: 'xiào', zhuyin: 'ㄒㄧㄠˋ', meaning: 'school', difficulty: 3, components: ['木', '交'] },
          { char: '學', pinyin: 'xué', zhuyin: 'ㄒㄩㄝˊ', meaning: 'to learn / study', difficulty: 3, components: ['臼', '冖', '子'] },
          // Page 3
          { char: '號', pinyin: 'hào', zhuyin: 'ㄏㄠˋ', meaning: 'number / date', difficulty: 3, components: ['口', '丂', '虎'] },
          { char: '月', pinyin: 'yuè', zhuyin: 'ㄩㄝˋ', meaning: 'moon / month', difficulty: 2, components: ['月'] },
          { char: '期', pinyin: 'qī', zhuyin: 'ㄑㄧ', meaning: 'period / week', difficulty: 3, components: ['其', '月'] },
          { char: '星', pinyin: 'xīng', zhuyin: 'ㄒㄧㄥ', meaning: 'star', difficulty: 3, components: ['日', '生'] },
          { char: '天', pinyin: 'tiān', zhuyin: 'ㄊㄧㄢ', meaning: 'day / sky', difficulty: 2, components: ['一', '大'] },
          { char: '今', pinyin: 'jīn', zhuyin: 'ㄐㄧㄣ', meaning: 'today / now', difficulty: 2, components: ['人', '一', '丶'] },
          // Page 4
          { char: '課', pinyin: 'kè', zhuyin: 'ㄎㄜˋ', meaning: 'class / lesson', difficulty: 4, components: ['言', '果'] },
          { char: '沒', pinyin: 'méi', zhuyin: 'ㄇㄟˊ', meaning: 'not have / no', difficulty: 2, components: ['氵', '殳'] },
          { char: '有', pinyin: 'yǒu', zhuyin: 'ㄧㄡˇ', meaning: 'to have / exist', difficulty: 2, components: ['ナ', '月'] },
          { char: '上', pinyin: 'shàng', zhuyin: 'ㄕㄤˋ', meaning: 'up / on / above', difficulty: 1, components: ['上'] },
          { char: '早', pinyin: 'zǎo', zhuyin: 'ㄗㄠˇ', meaning: 'early / morning', difficulty: 2, components: ['日', '十'] },
          { char: '日', pinyin: 'rì', zhuyin: 'ㄖˋ', meaning: 'sun / day', difficulty: 1, components: ['日'] },
          // Page 5
          { char: '回', pinyin: 'huí', zhuyin: 'ㄏㄨㄟˊ', meaning: 'to return', difficulty: 2, components: ['囗', '口'] },
          { char: '午', pinyin: 'wǔ', zhuyin: 'ㄨˇ', meaning: 'noon / midday', difficulty: 2, components: ['午'] },
          { char: '中', pinyin: 'zhōng', zhuyin: 'ㄓㄨㄥ', meaning: 'middle / center', difficulty: 2, components: ['丨', '口'] },
          { char: '館', pinyin: 'guǎn', zhuyin: 'ㄍㄨㄢˇ', meaning: 'hall / building', difficulty: 4, components: ['飠', '官'] },
          { char: '書', pinyin: 'shū', zhuyin: 'ㄕㄨ', meaning: 'book', difficulty: 3, components: ['聿', '曰'] },
          { char: '圖', pinyin: 'tú', zhuyin: 'ㄊㄨˊ', meaning: 'picture / map', difficulty: 3, components: ['囗', '啚'] },
          // Page 6
          { char: '機', pinyin: 'jī', zhuyin: 'ㄐㄧ', meaning: 'machine / opportunity', difficulty: 4, components: ['木', '幾'] },
          { char: '手', pinyin: 'shǒu', zhuyin: 'ㄕㄡˇ', meaning: 'hand', difficulty: 2, components: ['手'] },
          { char: '分', pinyin: 'fēn', zhuyin: 'ㄈㄣ', meaning: 'minute / to divide', difficulty: 2, components: ['八', '刀'] },
          { char: '下', pinyin: 'xià', zhuyin: 'ㄒㄧㄚˋ', meaning: 'down / below', difficulty: 1, components: ['一', '卜'] },
          { char: '家', pinyin: 'jiā', zhuyin: 'ㄐㄧㄚ', meaning: 'home / family', difficulty: 2, components: ['宀', '豕'] },
          { char: '人', pinyin: 'rén', zhuyin: 'ㄖㄣˊ', meaning: 'person', difficulty: 1, components: ['人'] },
        ]
      },
      {
        id: 'ws-5',
        name: 'Worksheet 5 (Jan 8)',
        characters: [
          // Daily activities and meals
          { char: '做', pinyin: 'zuò', zhuyin: 'ㄗㄨㄛˋ', meaning: 'to do / to make', difficulty: 2, components: ['亻', '故'] },
          { char: '歲', pinyin: 'suì', zhuyin: 'ㄙㄨㄟˋ', meaning: 'years old', difficulty: 3, components: ['止', '戌', '小'] },
          { char: '起', pinyin: 'qǐ', zhuyin: 'ㄑㄧˇ', meaning: 'to rise / to get up', difficulty: 2, components: ['走', '己'] },
          { char: '床', pinyin: 'chuáng', zhuyin: 'ㄔㄨㄤˊ', meaning: 'bed', difficulty: 2, components: ['广', '木'] },
          { char: '午', pinyin: 'wǔ', zhuyin: 'ㄨˇ', meaning: 'noon / midday', difficulty: 2, components: ['午'] },
          { char: '早', pinyin: 'zǎo', zhuyin: 'ㄗㄠˇ', meaning: 'early / morning', difficulty: 2, components: ['日', '十'] },
          { char: '晚', pinyin: 'wǎn', zhuyin: 'ㄨㄢˇ', meaning: 'evening / late', difficulty: 3, components: ['日', '免'] },
          { char: '飯', pinyin: 'fàn', zhuyin: 'ㄈㄢˋ', meaning: 'rice / meal', difficulty: 2, components: ['飠', '反'] },
          { char: '睡', pinyin: 'shuì', zhuyin: 'ㄕㄨㄟˋ', meaning: 'to sleep', difficulty: 3, components: ['目', '垂'] },
          { char: '覺', pinyin: 'jiào', zhuyin: 'ㄐㄧㄠˋ', meaning: 'sleep / to feel', difficulty: 3, components: ['臼', '冖', '見'] },
          { char: '忙', pinyin: 'máng', zhuyin: 'ㄇㄤˊ', meaning: 'busy', difficulty: 2, components: ['忄', '亡'] },
          { char: '累', pinyin: 'lèi', zhuyin: 'ㄌㄟˋ', meaning: 'tired', difficulty: 3, components: ['田', '糸'] },
        ]
      }
    ]
  },
  {
    id: 'test-group',
    name: 'Test (測驗)',
    description: 'Test packs to assess your character mastery.',
    icon: '📋',
    isSpecial: true,
    characters: [],
    sequences: [
      {
        id: 'test-1',
        name: 'Test Pack 1',
        characters: [
          // 大家
          { char: '大', pinyin: 'dà', zhuyin: 'ㄉㄚˋ', meaning: 'big / great', difficulty: 1, components: ['一', '人'] },
          { char: '家', pinyin: 'jiā', zhuyin: 'ㄐㄧㄚ', meaning: 'home / family', difficulty: 2, components: ['宀', '豕'] },
          // 朋友
          { char: '朋', pinyin: 'péng', zhuyin: 'ㄆㄥˊ', meaning: 'friend (part of 朋友)', difficulty: 2, components: ['月', '月'] },
          { char: '友', pinyin: 'yǒu', zhuyin: 'ㄧㄡˇ', meaning: 'friend (part of 朋友)', difficulty: 2, components: ['ナ', '又'] },
          // 愛
          { char: '愛', pinyin: 'ài', zhuyin: 'ㄞˋ', meaning: 'love', difficulty: 3, components: ['爫', '冖', '心', '夂'] },
          // 吃
          { char: '吃', pinyin: 'chī', zhuyin: 'ㄔ', meaning: 'to eat', difficulty: 2, components: ['口', '乞'] },
          // 水果
          { char: '水', pinyin: 'shuǐ', zhuyin: 'ㄕㄨㄟˇ', meaning: 'water', difficulty: 1, components: ['水'] },
          { char: '果', pinyin: 'guǒ', zhuyin: 'ㄍㄨㄛˇ', meaning: 'fruit / result', difficulty: 2, components: ['田', '木'] },
          // 喝
          { char: '喝', pinyin: 'hē', zhuyin: 'ㄏㄜ', meaning: 'to drink', difficulty: 3, components: ['口', '曷'] },
          // 茶
          { char: '茶', pinyin: 'chá', zhuyin: 'ㄔㄚˊ', meaning: 'tea', difficulty: 3, components: ['艹', '人', '木'] },
          // 謝謝
          { char: '謝', pinyin: 'xiè', zhuyin: 'ㄒㄧㄝˋ', meaning: 'to thank', difficulty: 4, components: ['言', '身', '寸'] },
          // 不客氣
          { char: '不', pinyin: 'bù', zhuyin: 'ㄅㄨˋ', meaning: 'not / no', difficulty: 1, components: ['一', '丨', '丿', '丶'] },
          { char: '客', pinyin: 'kè', zhuyin: 'ㄎㄜˋ', meaning: 'guest / customer', difficulty: 3, components: ['宀', '各'] },
          { char: '氣', pinyin: 'qì', zhuyin: 'ㄑㄧˋ', meaning: 'air / gas / energy', difficulty: 3, components: ['气', '米'] },
          // 珍珠奶茶
          { char: '珍', pinyin: 'zhēn', zhuyin: 'ㄓㄣ', meaning: 'precious / rare', difficulty: 3, components: ['王', '㐱'] },
          { char: '珠', pinyin: 'zhū', zhuyin: 'ㄓㄨ', meaning: 'pearl / bead', difficulty: 3, components: ['王', '朱'] },
          { char: '奶', pinyin: 'nǎi', zhuyin: 'ㄋㄞˇ', meaning: 'milk / grandmother', difficulty: 2, components: ['女', '乃'] },
          // 自我介紹
          { char: '自', pinyin: 'zì', zhuyin: 'ㄗˋ', meaning: 'self / from', difficulty: 2, components: ['自'] },
          { char: '我', pinyin: 'wǒ', zhuyin: 'ㄨㄛˇ', meaning: 'I / me', difficulty: 3, components: ['手', '戈'] },
          { char: '介', pinyin: 'jiè', zhuyin: 'ㄐㄧㄝˋ', meaning: 'between (part of 介紹)', difficulty: 2, components: ['人', '丨', '丨'] },
          { char: '紹', pinyin: 'shào', zhuyin: 'ㄕㄠˋ', meaning: 'to introduce (part of 介紹)', difficulty: 3, components: ['糹', '召'] },
          // 早安
          { char: '早', pinyin: 'zǎo', zhuyin: 'ㄗㄠˇ', meaning: 'early / morning', difficulty: 2, components: ['日', '十'] },
          { char: '安', pinyin: 'ān', zhuyin: 'ㄢ', meaning: 'peace / safe', difficulty: 2, components: ['宀', '女'] },
          // 午安
          { char: '午', pinyin: 'wǔ', zhuyin: 'ㄨˇ', meaning: 'noon / midday', difficulty: 2, components: ['午'] },
          // 晚安
          { char: '晚', pinyin: 'wǎn', zhuyin: 'ㄨㄢˇ', meaning: 'evening / late', difficulty: 3, components: ['日', '免'] },
        ]
      },
      {
        id: 'test-2',
        name: 'Test Pack 2',
        characters: [
          // Page 1
          { char: '要', pinyin: 'yào', zhuyin: 'ㄧㄠˋ', meaning: 'want / need', difficulty: 2 },
          { char: '末', pinyin: 'mò', zhuyin: 'ㄇㄛˋ', meaning: 'end / last', difficulty: 2, components: ['木', '一'] },
          { char: '週', pinyin: 'zhōu', zhuyin: 'ㄓㄡ', meaning: 'week', difficulty: 2, components: ['辶', '周'] },
          { char: '昨', pinyin: 'zuó', zhuyin: 'ㄗㄨㄛˊ', meaning: 'yesterday', difficulty: 2 },
          { char: '明', pinyin: 'míng', zhuyin: 'ㄇㄧㄥˊ', meaning: 'bright / tomorrow', difficulty: 2 },
          { char: '天', pinyin: 'tiān', zhuyin: 'ㄊㄧㄢ', meaning: 'day / sky', difficulty: 2, components: ['一', '大'] },
          // Page 2
          { char: '快', pinyin: 'kuài', zhuyin: 'ㄎㄨㄞˋ', meaning: 'fast', difficulty: 1, components: ['忄', '夬'] },
          { char: '日', pinyin: 'rì', zhuyin: 'ㄖˋ', meaning: 'sun / day', difficulty: 1, components: ['日'] },
          { char: '生', pinyin: 'shēng', zhuyin: 'ㄕㄥ', meaning: 'student / life', difficulty: 2 },
          { char: '的', pinyin: 'de', zhuyin: 'ㄉㄜ˙', meaning: 'possessive particle', difficulty: 1 },
          { char: '啊', pinyin: 'a', zhuyin: 'ㄚ˙', meaning: 'particle', difficulty: 1, components: ['口', '阿'] },
          { char: '來', pinyin: 'lái', zhuyin: 'ㄌㄞˊ', meaning: 'to come', difficulty: 2 },
          // Page 3
          { char: '題', pinyin: 'tí', zhuyin: 'ㄊㄧˊ', meaning: 'topic / problem', difficulty: 3, components: ['是', '頁'] },
          { char: '問', pinyin: 'wèn', zhuyin: 'ㄨㄣˋ', meaning: 'to ask', difficulty: 3, components: ['門', '口'] },
          { char: '沒', pinyin: 'méi', zhuyin: 'ㄇㄟˊ', meaning: 'not have / no', difficulty: 2, components: ['氵', '殳'] },
          { char: '上', pinyin: 'shàng', zhuyin: 'ㄕㄤˋ', meaning: 'up / on / above', difficulty: 1, components: ['上'] },
          { char: '晚', pinyin: 'wǎn', zhuyin: 'ㄨㄢˇ', meaning: 'evening / late', difficulty: 3, components: ['日', '免'] },
          { char: '樂', pinyin: 'lè', zhuyin: 'ㄌㄜˋ', meaning: 'happy / music', difficulty: 2, components: ['白', '幺', '木'] },
          // Page 4
          { char: '熱', pinyin: 'rè', zhuyin: 'ㄖㄜˋ', meaning: 'hot', difficulty: 3 },
          { char: '見', pinyin: 'jiàn', zhuyin: 'ㄐㄧㄢˋ', meaning: 'to see / meet', difficulty: 2 },
          { char: '再', pinyin: 'zài', zhuyin: 'ㄗㄞˋ', meaning: 'again / goodbye', difficulty: 2 },
        ]
      },
      {
        id: 'test-3',
        name: 'Test Pack 3 (Jan 8)',
        characters: [
          // Daily activities and meals
          { char: '做', pinyin: 'zuò', zhuyin: 'ㄗㄨㄛˋ', meaning: 'to do / to make', difficulty: 2, components: ['亻', '故'] },
          { char: '歲', pinyin: 'suì', zhuyin: 'ㄙㄨㄟˋ', meaning: 'years old', difficulty: 3, components: ['止', '戌', '小'] },
          { char: '起', pinyin: 'qǐ', zhuyin: 'ㄑㄧˇ', meaning: 'to rise / to get up', difficulty: 2, components: ['走', '己'] },
          { char: '床', pinyin: 'chuáng', zhuyin: 'ㄔㄨㄤˊ', meaning: 'bed', difficulty: 2, components: ['广', '木'] },
          { char: '午', pinyin: 'wǔ', zhuyin: 'ㄨˇ', meaning: 'noon / midday', difficulty: 2, components: ['午'] },
          { char: '早', pinyin: 'zǎo', zhuyin: 'ㄗㄠˇ', meaning: 'early / morning', difficulty: 2, components: ['日', '十'] },
          { char: '晚', pinyin: 'wǎn', zhuyin: 'ㄨㄢˇ', meaning: 'evening / late', difficulty: 3, components: ['日', '免'] },
          { char: '飯', pinyin: 'fàn', zhuyin: 'ㄈㄢˋ', meaning: 'rice / meal', difficulty: 2, components: ['飠', '反'] },
          { char: '睡', pinyin: 'shuì', zhuyin: 'ㄕㄨㄟˋ', meaning: 'to sleep', difficulty: 3, components: ['目', '垂'] },
          { char: '覺', pinyin: 'jiào', zhuyin: 'ㄐㄧㄠˋ', meaning: 'sleep / to feel', difficulty: 3, components: ['臼', '冖', '見'] },
          { char: '忙', pinyin: 'máng', zhuyin: 'ㄇㄤˊ', meaning: 'busy', difficulty: 2, components: ['忄', '亡'] },
          { char: '累', pinyin: 'lèi', zhuyin: 'ㄌㄟˋ', meaning: 'tired', difficulty: 3, components: ['田', '糸'] },
        ]
      }
    ]
  },
  {
    id: 'intro-basics',
    name: 'Introduction',
    description: 'Essential basics for getting started with writing.',
    icon: '🌱',
    characters: [
      { char: '一', pinyin: 'yī', zhuyin: 'ㄧ', meaning: 'one', difficulty: 1, components: ['一'] },
      { char: '二', pinyin: 'èr', zhuyin: 'ㄦˋ', meaning: 'two', difficulty: 1, components: ['一', '一'] },
      { char: '三', pinyin: 'sān', zhuyin: 'ㄙㄢ', meaning: 'three', difficulty: 1, components: ['一', '一', '一'] },
      { char: '人', pinyin: 'rén', zhuyin: 'ㄖㄣˊ', meaning: 'person', difficulty: 1, components: ['人'] },
      { char: '口', pinyin: 'kǒu', zhuyin: 'ㄎㄡˇ', meaning: 'mouth', difficulty: 1, components: ['口'] },
      { char: '日', pinyin: 'rì', zhuyin: 'ㄖˋ', meaning: 'sun / day', difficulty: 1, components: ['日'] },
      { char: '月', pinyin: 'yuè', zhuyin: 'ㄩㄝˋ', meaning: 'moon / month', difficulty: 2, components: ['月'] },
      { char: '山', pinyin: 'shān', zhuyin: 'ㄕㄢ', meaning: 'mountain', difficulty: 2, components: ['山'] },
      { char: '水', pinyin: 'shuǐ', zhuyin: 'ㄕㄨㄟˇ', meaning: 'water', difficulty: 2, components: ['水'] },
    ]
  },
  {
    id: 'hsk1',
    name: 'HSK 1',
    description: 'All 150 essential characters for HSK Level 1 proficiency.',
    icon: '📚',
    isSpecial: true,
    characters: [],
    sequences: [
      {
        id: 'hsk1-numbers',
        name: 'Numbers & Time',
        characters: [
          { char: '一', pinyin: 'yī', zhuyin: 'ㄧ', meaning: 'one', difficulty: 1 },
          { char: '二', pinyin: 'èr', zhuyin: 'ㄦˋ', meaning: 'two', difficulty: 1 },
          { char: '三', pinyin: 'sān', zhuyin: 'ㄙㄢ', meaning: 'three', difficulty: 1 },
          { char: '四', pinyin: 'sì', zhuyin: 'ㄙˋ', meaning: 'four', difficulty: 1 },
          { char: '五', pinyin: 'wǔ', zhuyin: 'ㄨˇ', meaning: 'five', difficulty: 1 },
          { char: '六', pinyin: 'liù', zhuyin: 'ㄌㄧㄡˋ', meaning: 'six', difficulty: 1 },
          { char: '七', pinyin: 'qī', zhuyin: 'ㄑㄧ', meaning: 'seven', difficulty: 1 },
          { char: '八', pinyin: 'bā', zhuyin: 'ㄅㄚ', meaning: 'eight', difficulty: 1 },
          { char: '九', pinyin: 'jiǔ', zhuyin: 'ㄐㄧㄡˇ', meaning: 'nine', difficulty: 1 },
          { char: '十', pinyin: 'shí', zhuyin: 'ㄕˊ', meaning: 'ten', difficulty: 1 },
          { char: '百', pinyin: 'bǎi', zhuyin: 'ㄅㄞˇ', meaning: 'hundred', difficulty: 2 },
          { char: '零', pinyin: 'líng', zhuyin: 'ㄌㄧㄥˊ', meaning: 'zero', difficulty: 2 },
          { char: '年', pinyin: 'nián', zhuyin: 'ㄋㄧㄢˊ', meaning: 'year', difficulty: 2 },
          { char: '月', pinyin: 'yuè', zhuyin: 'ㄩㄝˋ', meaning: 'month', difficulty: 1 },
          { char: '日', pinyin: 'rì', zhuyin: 'ㄖˋ', meaning: 'day / sun', difficulty: 1 },
          { char: '號', pinyin: 'hào', zhuyin: 'ㄏㄠˋ', meaning: 'number / date', difficulty: 3 },
          { char: '星', pinyin: 'xīng', zhuyin: 'ㄒㄧㄥ', meaning: 'star', difficulty: 2 },
          { char: '期', pinyin: 'qī', zhuyin: 'ㄑㄧ', meaning: 'period', difficulty: 2 },
          { char: '今', pinyin: 'jīn', zhuyin: 'ㄐㄧㄣ', meaning: 'today / now', difficulty: 1 },
          { char: '天', pinyin: 'tiān', zhuyin: 'ㄊㄧㄢ', meaning: 'day / sky', difficulty: 1 },
          { char: '昨', pinyin: 'zuó', zhuyin: 'ㄗㄨㄛˊ', meaning: 'yesterday', difficulty: 2 },
          { char: '明', pinyin: 'míng', zhuyin: 'ㄇㄧㄥˊ', meaning: 'bright / tomorrow', difficulty: 2 },
          { char: '時', pinyin: 'shí', zhuyin: 'ㄕˊ', meaning: 'time / hour', difficulty: 2 },
          { char: '候', pinyin: 'hòu', zhuyin: 'ㄏㄡˋ', meaning: 'time / wait', difficulty: 2 },
          { char: '分', pinyin: 'fēn', zhuyin: 'ㄈㄣ', meaning: 'minute / divide', difficulty: 2 },
          { char: '鐘', pinyin: 'zhōng', zhuyin: 'ㄓㄨㄥ', meaning: 'clock', difficulty: 3 },
          { char: '點', pinyin: 'diǎn', zhuyin: 'ㄉㄧㄢˇ', meaning: 'o\'clock / point', difficulty: 2 },
          { char: '半', pinyin: 'bàn', zhuyin: 'ㄅㄢˋ', meaning: 'half', difficulty: 1 },
          { char: '上', pinyin: 'shàng', zhuyin: 'ㄕㄤˋ', meaning: 'up / above', difficulty: 1 },
          { char: '下', pinyin: 'xià', zhuyin: 'ㄒㄧㄚˋ', meaning: 'down / below', difficulty: 1 },
        ]
      },
      {
        id: 'hsk1-people',
        name: 'People & Family',
        characters: [
          { char: '人', pinyin: 'rén', zhuyin: 'ㄖㄣˊ', meaning: 'person', difficulty: 1 },
          { char: '我', pinyin: 'wǒ', zhuyin: 'ㄨㄛˇ', meaning: 'I / me', difficulty: 2 },
          { char: '你', pinyin: 'nǐ', zhuyin: 'ㄋㄧˇ', meaning: 'you', difficulty: 2 },
          { char: '他', pinyin: 'tā', zhuyin: 'ㄊㄚ', meaning: 'he / him', difficulty: 1 },
          { char: '她', pinyin: 'tā', zhuyin: 'ㄊㄚ', meaning: 'she / her', difficulty: 2 },
          { char: '們', pinyin: 'men', zhuyin: 'ㄇㄣ˙', meaning: 'plural marker', difficulty: 2 },
          { char: '誰', pinyin: 'shéi', zhuyin: 'ㄕㄟˊ', meaning: 'who', difficulty: 3 },
          { char: '爸', pinyin: 'bà', zhuyin: 'ㄅㄚˋ', meaning: 'dad', difficulty: 2 },
          { char: '媽', pinyin: 'mā', zhuyin: 'ㄇㄚ', meaning: 'mom', difficulty: 2 },
          { char: '兒', pinyin: 'ér', zhuyin: 'ㄦˊ', meaning: 'son / child', difficulty: 2 },
          { char: '子', pinyin: 'zǐ', zhuyin: 'ㄗˇ', meaning: 'child / suffix', difficulty: 1 },
          { char: '女', pinyin: 'nǚ', zhuyin: 'ㄋㄩˇ', meaning: 'female / daughter', difficulty: 2 },
          { char: '家', pinyin: 'jiā', zhuyin: 'ㄐㄧㄚ', meaning: 'home / family', difficulty: 2 },
          { char: '朋', pinyin: 'péng', zhuyin: 'ㄆㄥˊ', meaning: 'friend (朋友)', difficulty: 2 },
          { char: '友', pinyin: 'yǒu', zhuyin: 'ㄧㄡˇ', meaning: 'friend (朋友)', difficulty: 2 },
          { char: '老', pinyin: 'lǎo', zhuyin: 'ㄌㄠˇ', meaning: 'old / teacher prefix', difficulty: 2 },
          { char: '師', pinyin: 'shī', zhuyin: 'ㄕ', meaning: 'teacher (老師)', difficulty: 2 },
          { char: '生', pinyin: 'shēng', zhuyin: 'ㄕㄥ', meaning: 'student / life', difficulty: 2 },
          { char: '學', pinyin: 'xué', zhuyin: 'ㄒㄩㄝˊ', meaning: 'study / learn', difficulty: 3 },
          { char: '同', pinyin: 'tóng', zhuyin: 'ㄊㄨㄥˊ', meaning: 'same', difficulty: 2 },
          { char: '先', pinyin: 'xiān', zhuyin: 'ㄒㄧㄢ', meaning: 'first / Mr.', difficulty: 2 },
          { char: '小', pinyin: 'xiǎo', zhuyin: 'ㄒㄧㄠˇ', meaning: 'small / young', difficulty: 1 },
          { char: '姐', pinyin: 'jiě', zhuyin: 'ㄐㄧㄝˇ', meaning: 'older sister / Miss', difficulty: 2 },
          { char: '名', pinyin: 'míng', zhuyin: 'ㄇㄧㄥˊ', meaning: 'name', difficulty: 2 },
          { char: '字', pinyin: 'zì', zhuyin: 'ㄗˋ', meaning: 'character / word', difficulty: 2 },
        ]
      },
      {
        id: 'hsk1-verbs',
        name: 'Common Verbs',
        characters: [
          { char: '是', pinyin: 'shì', zhuyin: 'ㄕˋ', meaning: 'to be', difficulty: 1 },
          { char: '有', pinyin: 'yǒu', zhuyin: 'ㄧㄡˇ', meaning: 'to have', difficulty: 2 },
          { char: '在', pinyin: 'zài', zhuyin: 'ㄗㄞˋ', meaning: 'at / in', difficulty: 1 },
          { char: '會', pinyin: 'huì', zhuyin: 'ㄏㄨㄟˋ', meaning: 'can / will', difficulty: 2 },
          { char: '能', pinyin: 'néng', zhuyin: 'ㄋㄥˊ', meaning: 'can / able', difficulty: 2 },
          { char: '想', pinyin: 'xiǎng', zhuyin: 'ㄒㄧㄤˇ', meaning: 'want / think', difficulty: 2 },
          { char: '要', pinyin: 'yào', zhuyin: 'ㄧㄠˋ', meaning: 'want / need', difficulty: 2 },
          { char: '去', pinyin: 'qù', zhuyin: 'ㄑㄩˋ', meaning: 'to go', difficulty: 1 },
          { char: '來', pinyin: 'lái', zhuyin: 'ㄌㄞˊ', meaning: 'to come', difficulty: 2 },
          { char: '回', pinyin: 'huí', zhuyin: 'ㄏㄨㄟˊ', meaning: 'to return', difficulty: 2 },
          { char: '看', pinyin: 'kàn', zhuyin: 'ㄎㄢˋ', meaning: 'to look / see', difficulty: 2 },
          { char: '見', pinyin: 'jiàn', zhuyin: 'ㄐㄧㄢˋ', meaning: 'to see / meet', difficulty: 2 },
          { char: '聽', pinyin: 'tīng', zhuyin: 'ㄊㄧㄥ', meaning: 'to listen', difficulty: 3 },
          { char: '說', pinyin: 'shuō', zhuyin: 'ㄕㄨㄛ', meaning: 'to speak / say', difficulty: 2 },
          { char: '讀', pinyin: 'dú', zhuyin: 'ㄉㄨˊ', meaning: 'to read', difficulty: 3 },
          { char: '寫', pinyin: 'xiě', zhuyin: 'ㄒㄧㄝˇ', meaning: 'to write', difficulty: 3 },
          { char: '做', pinyin: 'zuò', zhuyin: 'ㄗㄨㄛˋ', meaning: 'to do / make', difficulty: 2 },
          { char: '工', pinyin: 'gōng', zhuyin: 'ㄍㄨㄥ', meaning: 'work', difficulty: 1 },
          { char: '作', pinyin: 'zuò', zhuyin: 'ㄗㄨㄛˋ', meaning: 'work / do', difficulty: 2 },
          { char: '住', pinyin: 'zhù', zhuyin: 'ㄓㄨˋ', meaning: 'to live', difficulty: 2 },
          { char: '吃', pinyin: 'chī', zhuyin: 'ㄔ', meaning: 'to eat', difficulty: 2 },
          { char: '喝', pinyin: 'hē', zhuyin: 'ㄏㄜ', meaning: 'to drink', difficulty: 2 },
          { char: '睡', pinyin: 'shuì', zhuyin: 'ㄕㄨㄟˋ', meaning: 'to sleep', difficulty: 3 },
          { char: '覺', pinyin: 'jiào', zhuyin: 'ㄐㄧㄠˋ', meaning: 'sleep / feel', difficulty: 3 },
          { char: '坐', pinyin: 'zuò', zhuyin: 'ㄗㄨㄛˋ', meaning: 'to sit', difficulty: 2 },
          { char: '買', pinyin: 'mǎi', zhuyin: 'ㄇㄞˇ', meaning: 'to buy', difficulty: 2 },
          { char: '叫', pinyin: 'jiào', zhuyin: 'ㄐㄧㄠˋ', meaning: 'to call / name', difficulty: 2 },
          { char: '打', pinyin: 'dǎ', zhuyin: 'ㄉㄚˇ', meaning: 'to hit / make', difficulty: 2 },
          { char: '開', pinyin: 'kāi', zhuyin: 'ㄎㄞ', meaning: 'to open', difficulty: 2 },
          { char: '關', pinyin: 'guān', zhuyin: 'ㄍㄨㄢ', meaning: 'to close', difficulty: 3 },
          { char: '愛', pinyin: 'ài', zhuyin: 'ㄞˋ', meaning: 'to love', difficulty: 3 },
          { char: '喜', pinyin: 'xǐ', zhuyin: 'ㄒㄧˇ', meaning: 'happy / like', difficulty: 2 },
          { char: '歡', pinyin: 'huān', zhuyin: 'ㄏㄨㄢ', meaning: 'happy / like (喜歡)', difficulty: 3 },
        ]
      },
      {
        id: 'hsk1-adj-adv',
        name: 'Adjectives & Adverbs',
        characters: [
          { char: '好', pinyin: 'hǎo', zhuyin: 'ㄏㄠˇ', meaning: 'good / well', difficulty: 1 },
          { char: '大', pinyin: 'dà', zhuyin: 'ㄉㄚˋ', meaning: 'big / large', difficulty: 1 },
          { char: '多', pinyin: 'duō', zhuyin: 'ㄉㄨㄛ', meaning: 'many / much', difficulty: 1 },
          { char: '少', pinyin: 'shǎo', zhuyin: 'ㄕㄠˇ', meaning: 'few / little', difficulty: 2 },
          { char: '冷', pinyin: 'lěng', zhuyin: 'ㄌㄥˇ', meaning: 'cold', difficulty: 2 },
          { char: '熱', pinyin: 'rè', zhuyin: 'ㄖㄜˋ', meaning: 'hot', difficulty: 3 },
          { char: '高', pinyin: 'gāo', zhuyin: 'ㄍㄠ', meaning: 'tall / high', difficulty: 2 },
          { char: '漂', pinyin: 'piào', zhuyin: 'ㄆㄧㄠˋ', meaning: 'pretty (漂亮)', difficulty: 2 },
          { char: '亮', pinyin: 'liàng', zhuyin: 'ㄌㄧㄤˋ', meaning: 'bright (漂亮)', difficulty: 2 },
          { char: '很', pinyin: 'hěn', zhuyin: 'ㄏㄣˇ', meaning: 'very', difficulty: 2 },
          { char: '太', pinyin: 'tài', zhuyin: 'ㄊㄞˋ', meaning: 'too / very', difficulty: 1 },
          { char: '都', pinyin: 'dōu', zhuyin: 'ㄉㄡ', meaning: 'all / both', difficulty: 2 },
          { char: '不', pinyin: 'bù', zhuyin: 'ㄅㄨˋ', meaning: 'not', difficulty: 1 },
          { char: '沒', pinyin: 'méi', zhuyin: 'ㄇㄟˊ', meaning: 'not / no', difficulty: 2 },
          { char: '對', pinyin: 'duì', zhuyin: 'ㄉㄨㄟˋ', meaning: 'correct / right', difficulty: 2 },
        ]
      },
      {
        id: 'hsk1-nouns',
        name: 'Common Nouns',
        characters: [
          { char: '中', pinyin: 'zhōng', zhuyin: 'ㄓㄨㄥ', meaning: 'middle / China', difficulty: 1 },
          { char: '國', pinyin: 'guó', zhuyin: 'ㄍㄨㄛˊ', meaning: 'country', difficulty: 2 },
          { char: '北', pinyin: 'běi', zhuyin: 'ㄅㄟˇ', meaning: 'north', difficulty: 2 },
          { char: '京', pinyin: 'jīng', zhuyin: 'ㄐㄧㄥ', meaning: 'capital', difficulty: 2 },
          { char: '電', pinyin: 'diàn', zhuyin: 'ㄉㄧㄢˋ', meaning: 'electricity', difficulty: 3 },
          { char: '話', pinyin: 'huà', zhuyin: 'ㄏㄨㄚˋ', meaning: 'speech / words', difficulty: 2 },
          { char: '腦', pinyin: 'nǎo', zhuyin: 'ㄋㄠˇ', meaning: 'brain (電腦)', difficulty: 3 },
          { char: '視', pinyin: 'shì', zhuyin: 'ㄕˋ', meaning: 'view (電視)', difficulty: 2 },
          { char: '影', pinyin: 'yǐng', zhuyin: 'ㄧㄥˇ', meaning: 'shadow / movie', difficulty: 2 },
          { char: '院', pinyin: 'yuàn', zhuyin: 'ㄩㄢˋ', meaning: 'yard / hospital', difficulty: 2 },
          { char: '醫', pinyin: 'yī', zhuyin: 'ㄧ', meaning: 'doctor / medicine', difficulty: 3 },
          { char: '書', pinyin: 'shū', zhuyin: 'ㄕㄨ', meaning: 'book', difficulty: 2 },
          { char: '店', pinyin: 'diàn', zhuyin: 'ㄉㄧㄢˋ', meaning: 'shop / store', difficulty: 2 },
          { char: '飯', pinyin: 'fàn', zhuyin: 'ㄈㄢˋ', meaning: 'rice / meal', difficulty: 2 },
          { char: '館', pinyin: 'guǎn', zhuyin: 'ㄍㄨㄢˇ', meaning: 'hall / restaurant', difficulty: 3 },
          { char: '菜', pinyin: 'cài', zhuyin: 'ㄘㄞˋ', meaning: 'vegetable / dish', difficulty: 2 },
          { char: '茶', pinyin: 'chá', zhuyin: 'ㄔㄚˊ', meaning: 'tea', difficulty: 2 },
          { char: '水', pinyin: 'shuǐ', zhuyin: 'ㄕㄨㄟˇ', meaning: 'water', difficulty: 1 },
          { char: '果', pinyin: 'guǒ', zhuyin: 'ㄍㄨㄛˇ', meaning: 'fruit', difficulty: 2 },
          { char: '錢', pinyin: 'qián', zhuyin: 'ㄑㄧㄢˊ', meaning: 'money', difficulty: 3 },
          { char: '塊', pinyin: 'kuài', zhuyin: 'ㄎㄨㄞˋ', meaning: 'piece / yuan', difficulty: 2 },
          { char: '車', pinyin: 'chē', zhuyin: 'ㄔㄜ', meaning: 'car / vehicle', difficulty: 2 },
          { char: '機', pinyin: 'jī', zhuyin: 'ㄐㄧ', meaning: 'machine / plane', difficulty: 3 },
          { char: '場', pinyin: 'chǎng', zhuyin: 'ㄔㄤˇ', meaning: 'field / place', difficulty: 2 },
          { char: '雨', pinyin: 'yǔ', zhuyin: 'ㄩˇ', meaning: 'rain', difficulty: 2 },
          { char: '氣', pinyin: 'qì', zhuyin: 'ㄑㄧˋ', meaning: 'air / gas', difficulty: 2 },
          { char: '東', pinyin: 'dōng', zhuyin: 'ㄉㄨㄥ', meaning: 'east', difficulty: 2 },
          { char: '西', pinyin: 'xī', zhuyin: 'ㄒㄧ', meaning: 'west / thing', difficulty: 1 },
          { char: '前', pinyin: 'qián', zhuyin: 'ㄑㄧㄢˊ', meaning: 'front / before', difficulty: 2 },
          { char: '後', pinyin: 'hòu', zhuyin: 'ㄏㄡˋ', meaning: 'back / after', difficulty: 2 },
          { char: '面', pinyin: 'miàn', zhuyin: 'ㄇㄧㄢˋ', meaning: 'face / side', difficulty: 2 },
          { char: '裡', pinyin: 'lǐ', zhuyin: 'ㄌㄧˇ', meaning: 'inside', difficulty: 2 },
          { char: '桌', pinyin: 'zhuō', zhuyin: 'ㄓㄨㄛ', meaning: 'table', difficulty: 2 },
          { char: '椅', pinyin: 'yǐ', zhuyin: 'ㄧˇ', meaning: 'chair', difficulty: 3 },
        ]
      },
      {
        id: 'hsk1-grammar',
        name: 'Grammar & Particles',
        characters: [
          { char: '的', pinyin: 'de', zhuyin: 'ㄉㄜ˙', meaning: 'possessive particle', difficulty: 1 },
          { char: '了', pinyin: 'le', zhuyin: 'ㄌㄜ˙', meaning: 'completed action', difficulty: 2 },
          { char: '嗎', pinyin: 'ma', zhuyin: 'ㄇㄚ˙', meaning: 'question particle', difficulty: 1 },
          { char: '呢', pinyin: 'ne', zhuyin: 'ㄋㄜ˙', meaning: 'and you? / what about', difficulty: 2 },
          { char: '吧', pinyin: 'ba', zhuyin: 'ㄅㄚ˙', meaning: 'suggestion particle', difficulty: 2 },
          { char: '和', pinyin: 'hé', zhuyin: 'ㄏㄜˊ', meaning: 'and / with', difficulty: 2 },
          { char: '這', pinyin: 'zhè', zhuyin: 'ㄓㄜˋ', meaning: 'this', difficulty: 2 },
          { char: '那', pinyin: 'nà', zhuyin: 'ㄋㄚˋ', meaning: 'that', difficulty: 1 },
          { char: '哪', pinyin: 'nǎ', zhuyin: 'ㄋㄚˇ', meaning: 'which', difficulty: 2 },
          { char: '什', pinyin: 'shén', zhuyin: 'ㄕㄣˊ', meaning: 'what (什麼)', difficulty: 2 },
          { char: '麼', pinyin: 'me', zhuyin: 'ㄇㄜ˙', meaning: 'what (什麼)', difficulty: 2 },
          { char: '怎', pinyin: 'zěn', zhuyin: 'ㄗㄣˇ', meaning: 'how (怎麼)', difficulty: 2 },
          { char: '樣', pinyin: 'yàng', zhuyin: 'ㄧㄤˋ', meaning: 'kind / type (怎麼樣)', difficulty: 2 },
          { char: '幾', pinyin: 'jǐ', zhuyin: 'ㄐㄧˇ', meaning: 'how many', difficulty: 2 },
          { char: '個', pinyin: 'gè', zhuyin: 'ㄍㄜˋ', meaning: 'general classifier', difficulty: 1 },
          { char: '些', pinyin: 'xiē', zhuyin: 'ㄒㄧㄝ', meaning: 'some', difficulty: 2 },
          { char: '本', pinyin: 'běn', zhuyin: 'ㄅㄣˇ', meaning: 'classifier for books', difficulty: 2 },
          { char: '歲', pinyin: 'suì', zhuyin: 'ㄙㄨㄟˋ', meaning: 'years old', difficulty: 3 },
        ]
      },
      {
        id: 'hsk1-misc',
        name: 'Misc & Greetings',
        characters: [
          { char: '謝', pinyin: 'xiè', zhuyin: 'ㄒㄧㄝˋ', meaning: 'thank', difficulty: 3 },
          { char: '再', pinyin: 'zài', zhuyin: 'ㄗㄞˋ', meaning: 'again / goodbye', difficulty: 2 },
          { char: '請', pinyin: 'qǐng', zhuyin: 'ㄑㄧㄥˇ', meaning: 'please / invite', difficulty: 3 },
          { char: '對', pinyin: 'duì', zhuyin: 'ㄉㄨㄟˋ', meaning: 'correct / sorry', difficulty: 2 },
          { char: '起', pinyin: 'qǐ', zhuyin: 'ㄑㄧˇ', meaning: 'rise (對不起)', difficulty: 2 },
          { char: '沒', pinyin: 'méi', zhuyin: 'ㄇㄟˊ', meaning: 'not (沒關係)', difficulty: 2 },
          { char: '係', pinyin: 'xì', zhuyin: 'ㄒㄧˋ', meaning: 'relation (沒關係)', difficulty: 3 },
          { char: '現', pinyin: 'xiàn', zhuyin: 'ㄒㄧㄢˋ', meaning: 'now / appear', difficulty: 2 },
          { char: '正', pinyin: 'zhèng', zhuyin: 'ㄓㄥˋ', meaning: 'just / correct', difficulty: 2 },
          { char: '認', pinyin: 'rèn', zhuyin: 'ㄖㄣˋ', meaning: 'recognize (認識)', difficulty: 3 },
          { char: '識', pinyin: 'shí', zhuyin: 'ㄕˊ', meaning: 'know (認識)', difficulty: 3 },
        ]
      }
    ]
  },
  {
    id: 'zhuyin',
    name: 'Zhuyin (注音符號)',
    description: 'Learn Bopomofo - the Taiwanese phonetic system for pronunciation.',
    icon: 'ㄅ',
    characters: [],
    sequences: [
      {
        id: 'zhuyin-consonants',
        name: 'Consonants (聲母)',
        characters: [
          { char: 'ㄅ', pinyin: 'b', zhuyin: 'ㄅ', meaning: 'b as in "boy"', difficulty: 1 },
          { char: 'ㄆ', pinyin: 'p', zhuyin: 'ㄆ', meaning: 'p as in "pop"', difficulty: 1 },
          { char: 'ㄇ', pinyin: 'm', zhuyin: 'ㄇ', meaning: 'm as in "mom"', difficulty: 1 },
          { char: 'ㄈ', pinyin: 'f', zhuyin: 'ㄈ', meaning: 'f as in "fun"', difficulty: 1 },
          { char: 'ㄉ', pinyin: 'd', zhuyin: 'ㄉ', meaning: 'd as in "dog"', difficulty: 1 },
          { char: 'ㄊ', pinyin: 't', zhuyin: 'ㄊ', meaning: 't as in "top"', difficulty: 1 },
          { char: 'ㄋ', pinyin: 'n', zhuyin: 'ㄋ', meaning: 'n as in "no"', difficulty: 1 },
          { char: 'ㄌ', pinyin: 'l', zhuyin: 'ㄌ', meaning: 'l as in "love"', difficulty: 1 },
          { char: 'ㄍ', pinyin: 'g', zhuyin: 'ㄍ', meaning: 'g as in "go"', difficulty: 1 },
          { char: 'ㄎ', pinyin: 'k', zhuyin: 'ㄎ', meaning: 'k as in "key"', difficulty: 1 },
          { char: 'ㄏ', pinyin: 'h', zhuyin: 'ㄏ', meaning: 'h as in "hot"', difficulty: 1 },
          { char: 'ㄐ', pinyin: 'j', zhuyin: 'ㄐ', meaning: 'j as in "jeep"', difficulty: 1 },
          { char: 'ㄑ', pinyin: 'q', zhuyin: 'ㄑ', meaning: 'q (ch sound)', difficulty: 2 },
          { char: 'ㄒ', pinyin: 'x', zhuyin: 'ㄒ', meaning: 'x (sh sound)', difficulty: 2 },
          { char: 'ㄓ', pinyin: 'zh', zhuyin: 'ㄓ', meaning: 'zh (retroflex j)', difficulty: 2 },
          { char: 'ㄔ', pinyin: 'ch', zhuyin: 'ㄔ', meaning: 'ch (retroflex ch)', difficulty: 2 },
          { char: 'ㄕ', pinyin: 'sh', zhuyin: 'ㄕ', meaning: 'sh (retroflex sh)', difficulty: 2 },
          { char: 'ㄖ', pinyin: 'r', zhuyin: 'ㄖ', meaning: 'r (retroflex r)', difficulty: 2 },
          { char: 'ㄗ', pinyin: 'z', zhuyin: 'ㄗ', meaning: 'z as in "zoo"', difficulty: 1 },
          { char: 'ㄘ', pinyin: 'c', zhuyin: 'ㄘ', meaning: 'c (ts sound)', difficulty: 2 },
          { char: 'ㄙ', pinyin: 's', zhuyin: 'ㄙ', meaning: 's as in "sun"', difficulty: 1 },
        ]
      },
      {
        id: 'zhuyin-vowels',
        name: 'Vowels (韻母)',
        characters: [
          { char: 'ㄚ', pinyin: 'a', zhuyin: 'ㄚ', meaning: 'a as in "father"', difficulty: 1 },
          { char: 'ㄛ', pinyin: 'o', zhuyin: 'ㄛ', meaning: 'o as in "or"', difficulty: 1 },
          { char: 'ㄜ', pinyin: 'e', zhuyin: 'ㄜ', meaning: 'e as in "her"', difficulty: 1 },
          { char: 'ㄝ', pinyin: 'ê', zhuyin: 'ㄝ', meaning: 'ê as in "yeah"', difficulty: 2 },
          { char: 'ㄞ', pinyin: 'ai', zhuyin: 'ㄞ', meaning: 'ai as in "eye"', difficulty: 1 },
          { char: 'ㄟ', pinyin: 'ei', zhuyin: 'ㄟ', meaning: 'ei as in "way"', difficulty: 1 },
          { char: 'ㄠ', pinyin: 'ao', zhuyin: 'ㄠ', meaning: 'ao as in "cow"', difficulty: 1 },
          { char: 'ㄡ', pinyin: 'ou', zhuyin: 'ㄡ', meaning: 'ou as in "go"', difficulty: 1 },
          { char: 'ㄢ', pinyin: 'an', zhuyin: 'ㄢ', meaning: 'an as in "on"', difficulty: 1 },
          { char: 'ㄣ', pinyin: 'en', zhuyin: 'ㄣ', meaning: 'en as in "taken"', difficulty: 1 },
          { char: 'ㄤ', pinyin: 'ang', zhuyin: 'ㄤ', meaning: 'ang as in "song"', difficulty: 1 },
          { char: 'ㄥ', pinyin: 'eng', zhuyin: 'ㄥ', meaning: 'eng as in "sung"', difficulty: 1 },
          { char: 'ㄦ', pinyin: 'er', zhuyin: 'ㄦ', meaning: 'er as in "are"', difficulty: 2 },
          { char: 'ㄧ', pinyin: 'i', zhuyin: 'ㄧ', meaning: 'i as in "bee"', difficulty: 1 },
          { char: 'ㄨ', pinyin: 'u', zhuyin: 'ㄨ', meaning: 'u as in "too"', difficulty: 1 },
          { char: 'ㄩ', pinyin: 'ü', zhuyin: 'ㄩ', meaning: 'ü as in German "über"', difficulty: 2 },
        ]
      }
    ]
  }
];