import { CharacterData } from './types';

export const MODERN_CHINESE_VOCAB: CharacterData[] = [
    // A - B
    { char: '哎', pinyin: 'āi', zhuyin: 'ㄞ', meaning: 'Ah! / Alas!', difficulty: 1 },
    { char: '八', pinyin: 'bā', zhuyin: 'ㄅㄚ', meaning: 'eight', difficulty: 1 },
    { char: '把', pinyin: 'bǎ', zhuyin: 'ㄅㄚˇ', meaning: 'to hold / particle', difficulty: 2 },
    { char: '爸爸', pinyin: 'bàba', zhuyin: 'ㄅㄚˋ ㄅㄚ˙', meaning: 'father', difficulty: 1 },
    { char: '百', pinyin: 'bǎi', zhuyin: 'ㄅㄞˇ', meaning: 'hundred', difficulty: 1 },
    { char: '百貨公司', pinyin: 'bǎihuò gōngsī', zhuyin: 'ㄅㄞˇ ㄏㄨㄛˋ ㄍㄨㄥ ㄙ', meaning: 'department store', difficulty: 3 },
    { char: '白色', pinyin: 'báisè', zhuyin: 'ㄅㄞˊ ㄙㄜˋ', meaning: 'white color', difficulty: 2 },
    { char: '白', pinyin: 'bái', zhuyin: 'ㄅㄞˊ', meaning: 'white', difficulty: 1 },
    { char: '班', pinyin: 'bān', zhuyin: 'ㄅㄢ', meaning: 'class', difficulty: 2 },
    { char: '半', pinyin: 'bàn', zhuyin: 'ㄅㄢˋ', meaning: 'half', difficulty: 1 },
    { char: '辦法', pinyin: 'bànfǎ', zhuyin: 'ㄅㄢˋ ㄈㄚˇ', meaning: 'method / way', difficulty: 3 },
    { char: '幫', pinyin: 'bāng', zhuyin: 'ㄅㄤ', meaning: 'to help', difficulty: 2 },
    { char: '幫忙', pinyin: 'bāngmáng', zhuyin: 'ㄅㄤ ㄇㄤˊ', meaning: 'to help', difficulty: 2 },
    { char: '辦公室', pinyin: 'bàngōngshì', zhuyin: 'ㄅㄢˋ ㄍㄨㄥ ㄕˋ', meaning: 'office', difficulty: 3 },
    { char: '棒球', pinyin: 'bàngqiú', zhuyin: 'ㄅㄤˋ ㄑㄧㄡˊ', meaning: 'baseball', difficulty: 2 },
    { char: '包子', pinyin: 'bāozi', zhuyin: 'ㄅㄠ ㄗ˙', meaning: 'steamed bun', difficulty: 2 },
    { char: '報紙', pinyin: 'bàozhǐ', zhuyin: 'ㄅㄠˋ ㄓˇ', meaning: 'newspaper', difficulty: 3 },
    { char: '杯', pinyin: 'bēi', zhuyin: 'ㄅㄟ', meaning: 'cup / glass (measure word)', difficulty: 1 },
    { char: '杯子', pinyin: 'bēizi', zhuyin: 'ㄅㄟ ㄗ˙', meaning: 'cup / glass', difficulty: 1 },
    { char: '北', pinyin: 'běi', zhuyin: 'ㄅㄟˇ', meaning: 'north', difficulty: 1 },
    { char: '本', pinyin: 'běn', zhuyin: 'ㄅㄣˇ', meaning: 'measure word for books', difficulty: 1 },
    { char: '本來', pinyin: 'běnlái', zhuyin: 'ㄅㄣˇ ㄌㄞˊ', meaning: 'originally', difficulty: 3 },
    { char: '筆', pinyin: 'bǐ', zhuyin: 'ㄅㄧˇ', meaning: 'pen', difficulty: 1 },
    { char: '比', pinyin: 'bǐ', zhuyin: 'ㄅㄧˇ', meaning: 'to compare', difficulty: 2 },
    { char: '邊', pinyin: 'biān', zhuyin: 'ㄅㄧㄢ', meaning: 'side', difficulty: 2 },
    { char: '錶', pinyin: 'biǎo', zhuyin: 'ㄅㄧㄠˇ', meaning: 'watch', difficulty: 2 },
    { char: '表演', pinyin: 'biǎoyǎn', zhuyin: 'ㄅㄧㄠˇ ㄧㄢˇ', meaning: 'to perform', difficulty: 3 },
    { char: '別的', pinyin: 'biéde', zhuyin: 'ㄅㄧㄝˊ ㄉㄜ˙', meaning: 'other', difficulty: 2 },
    { char: '別人', pinyin: 'biérén', zhuyin: 'ㄅㄧㄝˊ ㄖㄣˊ', meaning: 'other people', difficulty: 2 },
    { char: '比較', pinyin: 'bǐjiào', zhuyin: 'ㄅㄧˇ ㄐㄧㄠˋ', meaning: 'relatively / to compare', difficulty: 3 },
    { char: '比賽', pinyin: 'bǐsài', zhuyin: 'ㄅㄧˇ ㄙㄞˋ', meaning: 'competition', difficulty: 3 },
    { char: '畢業', pinyin: 'bìyè', zhuyin: 'ㄅㄧˋ ㄧㄝˋ', meaning: 'to graduate', difficulty: 3 },
    { char: '鼻子', pinyin: 'bízi', zhuyin: 'ㄅㄧˊ ㄗ˙', meaning: 'nose', difficulty: 2 },
    { char: '冰淇淋', pinyin: 'bīngqílín', zhuyin: 'ㄅㄧㄥ ㄑㄧˊ ㄌㄧㄣˊ', meaning: 'ice cream', difficulty: 3 },
    { char: '博物館', pinyin: 'bówùguǎn', zhuyin: 'ㄅㄛˊ ㄨˋ ㄍㄨㄢˇ', meaning: 'museum', difficulty: 3 },
    { char: '不', pinyin: 'bù', zhuyin: 'ㄅㄨˋ', meaning: 'not', difficulty: 1 },
    { char: '不錯', pinyin: 'búcuò', zhuyin: 'ㄅㄨˊ ㄘㄨㄛˋ', meaning: 'not bad / pretty good', difficulty: 2 },
    { char: '不好意思', pinyin: 'bùhǎoyìsi', zhuyin: 'ㄅㄨˋ ㄏㄠˇ ㄧˋ ㄙ˙', meaning: 'excuse me / embarrassed', difficulty: 3 },
    { char: '不客氣', pinyin: 'búkèqi', zhuyin: 'ㄅㄨˊ ㄎㄜˋ ㄑㄧ˙', meaning: 'you are welcome', difficulty: 2 },
    { char: '不舒服', pinyin: 'bùshūfu', zhuyin: 'ㄅㄨˋ ㄕㄨ ㄈㄨ˙', meaning: 'uncomfortable', difficulty: 3 },
    { char: '不要', pinyin: 'búyào', zhuyin: 'ㄅㄨˊ ㄧㄠˋ', meaning: 'do not / don\'t want', difficulty: 1 },

    // C
    { char: '菜', pinyin: 'cài', zhuyin: 'ㄘㄞˋ', meaning: 'vegetable / dish', difficulty: 1 },
    { char: '菜單', pinyin: 'càidān', zhuyin: 'ㄘㄞˋ ㄉㄢ', meaning: 'menu', difficulty: 2 },
    { char: '參加', pinyin: 'cānjiā', zhuyin: 'ㄘㄢ ㄐㄧㄚ', meaning: 'to participate', difficulty: 3 },
    { char: '參觀', pinyin: 'cānguān', zhuyin: 'ㄘㄢ ㄍㄨㄢ', meaning: 'to visit', difficulty: 3 },
    { char: '餐廳', pinyin: 'cāntīng', zhuyin: 'ㄘㄢ ㄊㄧㄥ', meaning: 'restaurant', difficulty: 2 },
    { char: '廁所', pinyin: 'cèsuǒ', zhuyin: 'ㄘㄜˋ ㄙㄨㄛˇ', meaning: 'toilet', difficulty: 2 },
    { char: '茶', pinyin: 'chá', zhuyin: 'ㄔㄚˊ', meaning: 'tea', difficulty: 1 },
    { char: '查', pinyin: 'chá', zhuyin: 'ㄔㄚˊ', meaning: 'to check', difficulty: 2 },
    { char: '差不多', pinyin: 'chàbùduō', zhuyin: 'ㄔㄚˋ ㄅㄨˋ ㄉㄨㄛ', meaning: 'almost / about', difficulty: 3 },
    { char: '長', pinyin: 'cháng', zhuyin: 'ㄔㄤˊ', meaning: 'long', difficulty: 1 },
    { char: '常', pinyin: 'cháng', zhuyin: 'ㄔㄤˊ', meaning: 'often', difficulty: 1 },
    { char: '場', pinyin: 'chǎng', zhuyin: 'ㄔㄤˇ', meaning: 'field / measure word', difficulty: 2 },
    { char: '唱歌', pinyin: 'chànggē', zhuyin: 'ㄔㄤˋ ㄍㄜ', meaning: 'to sing', difficulty: 2 },
    { char: '超級市場', pinyin: 'chāojí shìchǎng', zhuyin: 'ㄔㄠ ㄐㄧˊ ㄕˋ ㄔㄤˇ', meaning: 'supermarket', difficulty: 3 },
    { char: '成績', pinyin: 'chéngjī', zhuyin: 'ㄔㄥˊ ㄐㄧ', meaning: 'grade / score', difficulty: 3 },
    { char: '城市', pinyin: 'chéngshì', zhuyin: 'ㄔㄥˊ ㄕˋ', meaning: 'city', difficulty: 2 },
    { char: '車子', pinyin: 'chēzi', zhuyin: 'ㄔㄜ ㄗ˙', meaning: 'car', difficulty: 1 },
    { char: '車站', pinyin: 'chēzhàn', zhuyin: 'ㄔㄜ ㄓㄢˋ', meaning: 'station', difficulty: 2 },
    { char: '吃', pinyin: 'chī', zhuyin: 'ㄔ', meaning: 'to eat', difficulty: 1 },
    { char: '遲到', pinyin: 'chídào', zhuyin: 'ㄔˊ ㄉㄠˋ', meaning: 'to arrive late', difficulty: 2 },
    { char: '出', pinyin: 'chū', zhuyin: 'ㄔㄨ', meaning: 'to go out / exit', difficulty: 1 },
    { char: '出來', pinyin: 'chūlái', zhuyin: 'ㄔㄨ ㄌㄞˊ', meaning: 'to come out', difficulty: 2 },
    { char: '出去', pinyin: 'chūqù', zhuyin: 'ㄔㄨ ㄑㄩˋ', meaning: 'to go out', difficulty: 2 },
    { char: '出生', pinyin: 'chūshēng', zhuyin: 'ㄔㄨ ㄕㄥ', meaning: 'to be born', difficulty: 2 },
    { char: '廚房', pinyin: 'chúfáng', zhuyin: 'ㄔㄨˊ ㄈㄤˊ', meaning: 'kitchen', difficulty: 2 },
    { char: '穿', pinyin: 'chuān', zhuyin: 'ㄔㄨㄢ', meaning: 'to wear', difficulty: 1 },
    { char: '床', pinyin: 'chuáng', zhuyin: 'ㄔㄨㄤˊ', meaning: 'bed', difficulty: 1 },
    { char: '窗戶', pinyin: 'chuānghù', zhuyin: 'ㄔㄨㄤ ㄏㄨˋ', meaning: 'window', difficulty: 2 },
    { char: '春', pinyin: 'chūn', zhuyin: 'ㄔㄨㄣ', meaning: 'spring', difficulty: 1 },
    { char: '次', pinyin: 'cì', zhuyin: 'ㄘˋ', meaning: 'time (frequency)', difficulty: 1 },
    { char: '聰明', pinyin: 'cōngmíng', zhuyin: 'ㄘㄨㄥ ㄇㄧㄥˊ', meaning: 'smart', difficulty: 2 },
    { char: '從', pinyin: 'cóng', zhuyin: 'ㄘㄨㄥˊ', meaning: 'from', difficulty: 1 },
    { char: '錯', pinyin: 'cuò', zhuyin: 'ㄘㄨㄛˋ', meaning: 'wrong', difficulty: 1 },

    // D
    { char: '打', pinyin: 'dǎ', zhuyin: 'ㄉㄚˇ', meaning: 'to hit / to play (ball)', difficulty: 1 },
    { char: '打電話', pinyin: 'dǎ diànhuà', zhuyin: 'ㄉㄚˇ ㄉㄧㄢˋ ㄏㄨㄚˋ', meaning: 'to make a phone call', difficulty: 2 },
    { char: '打開', pinyin: 'dǎkāi', zhuyin: 'ㄉㄚˇ ㄎㄞ', meaning: 'to open', difficulty: 2 },
    { char: '打算', pinyin: 'dǎsuàn', zhuyin: 'ㄉㄚˇ ㄙㄨㄢˋ', meaning: 'to plan', difficulty: 2 },
    { char: '大', pinyin: 'dà', zhuyin: 'ㄉㄚˋ', meaning: 'big', difficulty: 1 },
    { char: '大家', pinyin: 'dàjiā', zhuyin: 'ㄉㄚˋ ㄐㄧㄚ', meaning: 'everyone', difficulty: 2 },
    { char: '大樓', pinyin: 'dàlóu', zhuyin: 'ㄉㄚˋ ㄌㄡˊ', meaning: 'building', difficulty: 2 },
    { char: '大人', pinyin: 'dàrén', zhuyin: 'ㄉㄚˋ ㄖㄣˊ', meaning: 'adult', difficulty: 2 },
    { char: '大聲', pinyin: 'dàshēng', zhuyin: 'ㄉㄚˋ ㄕㄥ', meaning: 'loud', difficulty: 2 },
    { char: '大學', pinyin: 'dàxué', zhuyin: 'ㄉㄚˋ ㄒㄩㄝˊ', meaning: 'university', difficulty: 2 },
    { char: '帶', pinyin: 'dài', zhuyin: 'ㄉㄞˋ', meaning: 'to bring', difficulty: 2 },
    { char: '戴', pinyin: 'dài', zhuyin: 'ㄉㄞˋ', meaning: 'to wear (accessories)', difficulty: 2 },
    { char: '代表', pinyin: 'dàibiǎo', zhuyin: 'ㄉㄞˋ ㄅㄧㄠˇ', meaning: 'to represent', difficulty: 3 },
    { char: '擔心', pinyin: 'dānxīn', zhuyin: 'ㄉㄢ ㄒㄧㄣ', meaning: 'to worry', difficulty: 2 },
    { char: '蛋', pinyin: 'dàn', zhuyin: 'ㄉㄢˋ', meaning: 'egg', difficulty: 1 },
    { char: '蛋糕', pinyin: 'dàngāo', zhuyin: 'ㄉㄢˋ ㄍㄠ', meaning: 'cake', difficulty: 2 },
    { char: '但是', pinyin: 'dànshì', zhuyin: 'ㄉㄢˋ ㄕˋ', meaning: 'but', difficulty: 1 },
    { char: '當', pinyin: 'dāng', zhuyin: 'ㄉㄤ', meaning: 'to be / to act as', difficulty: 2 },
    { char: '到', pinyin: 'dào', zhuyin: 'ㄉㄠˋ', meaning: 'to arrive', difficulty: 1 },
    { char: '的', pinyin: 'de', zhuyin: 'ㄉㄜ˙', meaning: 'possessive particle', difficulty: 1 },
    { char: '得', pinyin: 'de', zhuyin: 'ㄉㄜ˙', meaning: 'particle for degree', difficulty: 1 },
    { char: '燈', pinyin: 'dēng', zhuyin: 'ㄉㄥ', meaning: 'light / lamp', difficulty: 1 },
    { char: '等', pinyin: 'děng', zhuyin: 'ㄉㄥˇ', meaning: 'to wait', difficulty: 1 },
    { char: '第', pinyin: 'dì', zhuyin: 'ㄉㄧˋ', meaning: 'prefix for ordinal numbers', difficulty: 2 },
    { char: '弟弟', pinyin: 'dìdi', zhuyin: 'ㄉㄧˋ ㄉㄧ˙', meaning: 'younger brother', difficulty: 1 },
    { char: '地方', pinyin: 'dìfāng', zhuyin: 'ㄉㄧˋ ㄈㄤ', meaning: 'place', difficulty: 1 },
    { char: '地鐵', pinyin: 'dìtiě', zhuyin: 'ㄉㄧˋ ㄊㄧㄝˇ', meaning: 'subway', difficulty: 2 },
    { char: '地圖', pinyin: 'dìtú', zhuyin: 'ㄉㄧˋ ㄊㄨˊ', meaning: 'map', difficulty: 2 },
    { char: '地址', pinyin: 'dìzhǐ', zhuyin: 'ㄉㄧˋ ㄓˇ', meaning: 'address', difficulty: 2 },
    { char: '點', pinyin: 'diǎn', zhuyin: 'ㄉㄧㄢˇ', meaning: 'o\'clock / dot', difficulty: 1 },
    { char: '點菜', pinyin: 'diǎncài', zhuyin: 'ㄉㄧㄢˇ ㄘㄞˋ', meaning: 'to order food', difficulty: 2 },
    { char: '點心', pinyin: 'diǎnxīn', zhuyin: 'ㄉㄧㄢˇ ㄒㄧㄣ', meaning: 'snack', difficulty: 2 },
    { char: '電', pinyin: 'diàn', zhuyin: 'ㄉㄧㄢˋ', meaning: 'electricity', difficulty: 1 },
    { char: '電話', pinyin: 'diànhuà', zhuyin: 'ㄉㄧㄢˋ ㄏㄨㄚˋ', meaning: 'telephone', difficulty: 1 },
    { char: '電腦', pinyin: 'diànnǎo', zhuyin: 'ㄉㄧㄢˋ ㄋㄠˇ', meaning: 'computer', difficulty: 2 },
    { char: '電視', pinyin: 'diànshì', zhuyin: 'ㄉㄧㄢˋ ㄕˋ', meaning: 'television', difficulty: 1 },
    { char: '電梯', pinyin: 'diàntī', zhuyin: 'ㄉㄧㄢˋ ㄊㄧ', meaning: 'elevator', difficulty: 2 },
    { char: '電影', pinyin: 'diànyǐng', zhuyin: 'ㄉㄧㄢˋ ㄧㄥˇ', meaning: 'movie', difficulty: 1 },
    { char: '電影院', pinyin: 'diànyǐngyuàn', zhuyin: 'ㄉㄧㄢˋ ㄧㄥˇ ㄩㄢˋ', meaning: 'movie theater', difficulty: 2 },
    { char: '電子郵件', pinyin: 'diànzǐ yóujiàn', zhuyin: 'ㄉㄧㄢˋ ㄗˇ ㄧㄡˊ ㄐㄧㄢˋ', meaning: 'email', difficulty: 3 },

    // E
    { char: '餓', pinyin: 'è', zhuyin: 'ㄜˋ', meaning: 'hungry', difficulty: 1 },
    { char: '二', pinyin: 'èr', zhuyin: 'ㄦˋ', meaning: 'two', difficulty: 1 },
    { char: '耳朵', pinyin: 'ěrduo', zhuyin: 'ㄦˇ ㄉㄨㄛ˙', meaning: 'ear', difficulty: 2 },

    // F
    { char: '發燒', pinyin: 'fāshāo', zhuyin: 'ㄈㄚ ㄕㄠ', meaning: 'fever', difficulty: 3 },
    { char: '飯', pinyin: 'fàn', zhuyin: 'ㄈㄢˋ', meaning: 'rice / meal', difficulty: 1 },
    { char: '飯店', pinyin: 'fàndiàn', zhuyin: 'ㄈㄢˋ ㄉㄧㄢˋ', meaning: 'hotel / restaurant', difficulty: 2 },
    { char: '飯館', pinyin: 'fànguǎn', zhuyin: 'ㄈㄢˋ ㄍㄨㄢˇ', meaning: 'restaurant', difficulty: 2 },
    { char: '方便', pinyin: 'fāngbiàn', zhuyin: 'ㄈㄤ ㄅㄧㄢˋ', meaning: 'convenient', difficulty: 2 },
    { char: '房間', pinyin: 'fángjiān', zhuyin: 'ㄈㄤˊ ㄐㄧㄢ', meaning: 'room', difficulty: 2 },
    { char: '放', pinyin: 'fàng', zhuyin: 'ㄈㄤˋ', meaning: 'to put', difficulty: 2 },
    { char: '放假', pinyin: 'fàngjià', zhuyin: 'ㄈㄤˋ ㄐㄧㄚˋ', meaning: 'to have a holiday', difficulty: 2 },
    { char: '方向', pinyin: 'fāngxiàng', zhuyin: 'ㄈㄤ ㄒㄧㄤˋ', meaning: 'direction', difficulty: 3 },
    { char: '房子', pinyin: 'fángzi', zhuyin: 'ㄈㄤˊ ㄗ˙', meaning: 'house', difficulty: 2 },
    { char: '飛', pinyin: 'fēi', zhuyin: 'ㄈㄟ', meaning: 'to fly', difficulty: 2 },
    { char: '非常', pinyin: 'fēicháng', zhuyin: 'ㄈㄟ ㄔㄤˊ', meaning: 'very', difficulty: 2 },
    { char: '飛機', pinyin: 'fēijī', zhuyin: 'ㄈㄟ ㄐㄧ', meaning: 'airplane', difficulty: 1 },
    { char: '飛機場', pinyin: 'fēijīchǎng', zhuyin: 'ㄈㄟ ㄐㄧ ㄔㄤˇ', meaning: 'airport', difficulty: 2 },
    { char: '菲律賓', pinyin: 'Fēilǜbīn', zhuyin: 'ㄈㄟ ㄌㄩˋ ㄅㄧㄣ', meaning: 'Philippines', difficulty: 3 },
    { char: '分', pinyin: 'fēn', zhuyin: 'ㄈㄣ', meaning: 'minute / point', difficulty: 1 },
    { char: '吩', pinyin: 'fēn', zhuyin: 'ㄈㄣ', meaning: 'to order', difficulty: 3 },
    { char: '一份', pinyin: 'yífèn', zhuyin: 'ㄧˊ ㄈㄣˋ', meaning: 'a portion', difficulty: 2 },
    { char: '封', pinyin: 'fēng', zhuyin: 'ㄈㄥ', meaning: 'measure word for letters', difficulty: 2 },
    { char: '風', pinyin: 'fēng', zhuyin: 'ㄈㄥ', meaning: 'wind', difficulty: 2 },
    { char: '風景', pinyin: 'fēngjǐng', zhuyin: 'ㄈㄥ ㄐㄧㄥˇ', meaning: 'scenery', difficulty: 3 },
    { char: '分鐘', pinyin: 'fēnzhōng', zhuyin: 'ㄈㄣ ㄓㄨㄥ', meaning: 'minute', difficulty: 1 },
    { char: '付', pinyin: 'fù', zhuyin: 'ㄈㄨˋ', meaning: 'to pay', difficulty: 2 },
    { char: '附近', pinyin: 'fùjìn', zhuyin: 'ㄈㄨˋ ㄐㄧㄣˋ', meaning: 'nearby', difficulty: 2 },
    { char: '父母', pinyin: 'fùmǔ', zhuyin: 'ㄈㄨˋ ㄇㄨˇ', meaning: 'parents', difficulty: 2 },
    { char: '父親', pinyin: 'fùqīn', zhuyin: 'ㄈㄨˋ ㄑㄧㄣ', meaning: 'father', difficulty: 2 },

    // G
    { char: '剛才', pinyin: 'gāngcái', zhuyin: 'ㄍㄤ ㄘㄞˊ', meaning: 'just now', difficulty: 2 },
    { char: '剛剛', pinyin: 'gānggāng', zhuyin: 'ㄍㄤ ㄍㄤ', meaning: 'just now', difficulty: 2 },
    { char: '乾淨', pinyin: 'gānjìng', zhuyin: 'ㄍㄢ ㄐㄧㄥˋ', meaning: 'clean', difficulty: 2 },
    { char: '感冒', pinyin: 'gǎnmào', zhuyin: 'ㄍㄢˇ ㄇㄠˋ', meaning: 'to have a cold', difficulty: 2 },
    { char: '高', pinyin: 'gāo', zhuyin: 'ㄍㄠ', meaning: 'tall / high', difficulty: 1 },
    { char: '告訴', pinyin: 'gàosù', zhuyin: 'ㄍㄠˋ ㄙㄨˋ', meaning: 'to tell', difficulty: 2 },
    { char: '高鐵', pinyin: 'gāotiě', zhuyin: 'ㄍㄠ ㄊㄧㄝˇ', meaning: 'HSR (High Speed Rail)', difficulty: 2 },
    { char: '高興', pinyin: 'gāoxìng', zhuyin: 'ㄍㄠ ㄒㄧㄥˋ', meaning: 'happy', difficulty: 1 },
    { char: '高雄', pinyin: 'Gāoxióng', zhuyin: 'ㄍㄠ ㄒㄩㄥˊ', meaning: 'Kaohsiung', difficulty: 2 },
    { char: '歌', pinyin: 'gē', zhuyin: 'ㄍㄜ', meaning: 'song', difficulty: 2 },
    { char: '個', pinyin: 'gè', zhuyin: 'ㄍㄜˋ', meaning: 'measure word', difficulty: 1 },
    { char: '哥哥', pinyin: 'gēge', zhuyin: 'ㄍㄜ ㄍㄜ˙', meaning: 'older brother', difficulty: 1 },
    { char: '給', pinyin: 'gěi', zhuyin: 'ㄍㄟˇ', meaning: 'to give', difficulty: 1 },
    { char: '跟', pinyin: 'gēn', zhuyin: 'ㄍㄣ', meaning: 'with / and', difficulty: 1 },
    { char: '更', pinyin: 'gèng', zhuyin: 'ㄍㄥˋ', meaning: 'more', difficulty: 2 },
    { char: '工廠', pinyin: 'gōngchǎng', zhuyin: 'ㄍㄨㄥ ㄔㄤˇ', meaning: 'factory', difficulty: 3 },
    { char: '公共汽車', pinyin: 'gōnggòng qìchē', zhuyin: 'ㄍㄨㄥ ㄍㄨㄥˋ ㄑㄧˋ ㄔㄜ', meaning: 'public bus', difficulty: 2 },
    { char: '公車', pinyin: 'gōngchē', zhuyin: 'ㄍㄨㄥ ㄔㄜ', meaning: 'bus', difficulty: 1 },
    { char: '公尺', pinyin: 'gōngchǐ', zhuyin: 'ㄍㄨㄥ ㄔˇ', meaning: 'meter', difficulty: 2 },
    { char: '公分', pinyin: 'gōngfēn', zhuyin: 'ㄍㄨㄥ ㄈㄣ', meaning: 'centimeter', difficulty: 2 },
    { char: '公斤', pinyin: 'gōngjīn', zhuyin: 'ㄍㄨㄥ ㄐㄧㄣ', meaning: 'kilogram', difficulty: 2 },
    { char: '功課', pinyin: 'gōngkè', zhuyin: 'ㄍㄨㄥ ㄎㄜˋ', meaning: 'homework', difficulty: 2 },
    { char: '公里', pinyin: 'gōnglǐ', zhuyin: 'ㄍㄨㄥ ㄌㄧˇ', meaning: 'kilometer', difficulty: 2 },
    { char: '工人', pinyin: 'gōngrén', zhuyin: 'ㄍㄨㄥ ㄖㄣˊ', meaning: 'worker', difficulty: 2 },
    { char: '公司', pinyin: 'gōngsī', zhuyin: 'ㄍㄨㄥ ㄙ', meaning: 'company', difficulty: 2 },
    { char: '公園', pinyin: 'gōngyuán', zhuyin: 'ㄍㄨㄥ ㄩㄢˊ', meaning: 'park', difficulty: 1 },
    { char: '工作', pinyin: 'gōngzuò', zhuyin: 'ㄍㄨㄥ ㄗㄨㄛˋ', meaning: 'job / to work', difficulty: 1 },
    { char: '夠', pinyin: 'gòu', zhuyin: 'ㄍㄡˋ', meaning: 'enough', difficulty: 2 },
    { char: '狗', pinyin: 'gǒu', zhuyin: 'ㄍㄡˇ', meaning: 'dog', difficulty: 1 },
    { char: '關', pinyin: 'guān', zhuyin: 'ㄍㄨㄢ', meaning: 'to close', difficulty: 2 },
    { char: '貴', pinyin: 'guì', zhuyin: 'ㄍㄨㄟˋ', meaning: 'expensive', difficulty: 2 },
    { char: '過', pinyin: 'guò', zhuyin: 'ㄍㄨㄛˋ', meaning: 'to pass / particle', difficulty: 1 },
    { char: '國家', pinyin: 'guójiā', zhuyin: 'ㄍㄨㄛˊ ㄐㄧㄚ', meaning: 'country', difficulty: 2 },
    { char: '果汁', pinyin: 'guǒzhī', zhuyin: 'ㄍㄨㄛˇ ㄓ', meaning: 'juice', difficulty: 2 },
    { char: '故事', pinyin: 'gùshì', zhuyin: 'ㄍㄨˋ ㄕˋ', meaning: 'story', difficulty: 2 },

    // H
    { char: '還是', pinyin: 'háishì', zhuyin: 'ㄏㄞˊ ㄕˋ', meaning: 'or / still', difficulty: 2 },
    { char: '還', pinyin: 'hái', zhuyin: 'ㄏㄞˊ', meaning: 'still / yet', difficulty: 1 },
    { char: '海', pinyin: 'hǎi', zhuyin: 'ㄏㄞˇ', meaning: 'sea', difficulty: 2 },
    { char: '海邊', pinyin: 'hǎibiān', zhuyin: 'ㄏㄞˇ ㄅㄧㄢ', meaning: 'seaside', difficulty: 2 },
    { char: '還沒', pinyin: 'háiméi', zhuyin: 'ㄏㄞˊ ㄇㄟˊ', meaning: 'not yet', difficulty: 2 },
    { char: '孩子', pinyin: 'háizi', zhuyin: 'ㄏㄞˊ ㄗ˙', meaning: 'child', difficulty: 2 },
    { char: '韓國', pinyin: 'Hánguó', zhuyin: 'ㄏㄢˊ ㄍㄨㄛˊ', meaning: 'Korea', difficulty: 2 },
    { char: '好', pinyin: 'hǎo', zhuyin: 'ㄏㄠˇ', meaning: 'good', difficulty: 1 },
    { char: '好了', pinyin: 'hǎole', zhuyin: 'ㄏㄠˇ ㄌㄜ˙', meaning: 'okay / ready', difficulty: 1 },
    { char: '好吃', pinyin: 'hǎochī', zhuyin: 'ㄏㄠˇ ㄔ', meaning: 'delicious', difficulty: 1 },
    { char: '好喝', pinyin: 'hǎohē', zhuyin: 'ㄏㄠˇ ㄏㄜ', meaning: 'tasty (drink)', difficulty: 1 },
    { char: '好看', pinyin: 'hǎokàn', zhuyin: 'ㄏㄠˇ ㄎㄢˋ', meaning: 'good looking', difficulty: 1 },
    { char: '號碼', pinyin: 'hàomǎ', zhuyin: 'ㄏㄠˋ ㄇㄚˇ', meaning: 'number', difficulty: 2 },
    { char: '好玩', pinyin: 'hǎowán', zhuyin: 'ㄏㄠˇ ㄨㄢˊ', meaning: 'fun', difficulty: 1 },
    { char: '喝', pinyin: 'hē', zhuyin: 'ㄏㄜ', meaning: 'to drink', difficulty: 1 },
    { char: '和', pinyin: 'hé', zhuyin: 'ㄏㄜˊ', meaning: 'and', difficulty: 1 },
    { char: '河', pinyin: 'hé', zhuyin: 'ㄏㄜˊ', meaning: 'river', difficulty: 2 },
    { char: '合歡山', pinyin: 'Héhuān Shān', zhuyin: 'ㄏㄜˊ ㄏㄨㄢ ㄕㄢ', meaning: 'Hehuan Mountain', difficulty: 3 },
    { char: '黑', pinyin: 'hēi', zhuyin: 'ㄏㄟ', meaning: 'black', difficulty: 1 },
    { char: '黑板', pinyin: 'hēibǎn', zhuyin: 'ㄏㄟ ㄅㄢˇ', meaning: 'blackboard', difficulty: 2 },
    { char: '黑色', pinyin: 'hēisè', zhuyin: 'ㄏㄟ ㄙㄜˋ', meaning: 'black color', difficulty: 2 },
    { char: '荷蘭', pinyin: 'Hélán', zhuyin: 'ㄏㄜˊ ㄌㄢˊ', meaning: 'Netherlands', difficulty: 3 },
    { char: '很', pinyin: 'hěn', zhuyin: 'ㄏㄣˇ', meaning: 'very', difficulty: 1 },
    { char: '紅茶', pinyin: 'hóngchá', zhuyin: 'ㄏㄨㄥˊ ㄔㄚˊ', meaning: 'black tea', difficulty: 2 },
    { char: '紅色', pinyin: 'hóngsè', zhuyin: 'ㄏㄨㄥˊ ㄙㄜˋ', meaning: 'red color', difficulty: 2 },
    { char: '紅', pinyin: 'hóng', zhuyin: 'ㄏㄨㄥˊ', meaning: 'red', difficulty: 1 },
    { char: '後面', pinyin: 'hòumiàn', zhuyin: 'ㄏㄡˋ ㄇㄧㄢˋ', meaning: 'behind', difficulty: 1 },
    { char: '後來', pinyin: 'hòulái', zhuyin: 'ㄏㄡˋ ㄌㄞˊ', meaning: 'later', difficulty: 2 },
    { char: '後天', pinyin: 'hòutiān', zhuyin: 'ㄏㄡˋ ㄊㄧㄢ', meaning: 'day after tomorrow', difficulty: 2 },
    { char: '湖', pinyin: 'hú', zhuyin: 'ㄏㄨˊ', meaning: 'lake', difficulty: 2 },
    { char: '虎', pinyin: 'hǔ', zhuyin: 'ㄏㄨˇ', meaning: 'tiger', difficulty: 2 },
    { char: '花', pinyin: 'huā', zhuyin: 'ㄏㄨㄚ', meaning: 'flower', difficulty: 1 },
    { char: '畫', pinyin: 'huà', zhuyin: 'ㄏㄨㄚˋ', meaning: 'to paint / draw', difficulty: 2 },
    { char: '畫畫', pinyin: 'huàhuà', zhuyin: 'ㄏㄨㄚˋ ㄏㄨㄚˋ', meaning: 'to paint / draw', difficulty: 2 },
    { char: '壞', pinyin: 'huài', zhuyin: 'ㄏㄨㄞˋ', meaning: 'bad / broken', difficulty: 2 },
    { char: '環境', pinyin: 'huánjìng', zhuyin: 'ㄏㄨㄢˊ ㄐㄧㄥˋ', meaning: 'environment', difficulty: 3 },
    { char: '換', pinyin: 'huàn', zhuyin: 'ㄏㄨㄢˋ', meaning: 'to change / exchange', difficulty: 2 },
    { char: '黃', pinyin: 'huáng', zhuyin: 'ㄏㄨㄤˊ', meaning: 'yellow', difficulty: 1 },
    { char: '黃色', pinyin: 'huángsè', zhuyin: 'ㄏㄨㄤˊ ㄙㄜˋ', meaning: 'yellow color', difficulty: 2 },
    { char: '歡迎', pinyin: 'huānyíng', zhuyin: 'ㄏㄨㄢ ㄧㄥˊ', meaning: 'welcome', difficulty: 2 },
    { char: '華人', pinyin: 'Huárén', zhuyin: 'ㄏㄨㄚˊ ㄖㄣˊ', meaning: 'Chinese / ethnic Chinese', difficulty: 3 },
    { char: '華語', pinyin: 'Huáyǔ', zhuyin: 'ㄏㄨㄚˊ ㄩˇ', meaning: 'Chinese language', difficulty: 2 },
    { char: '會', pinyin: 'huì', zhuyin: 'ㄏㄨㄟˋ', meaning: 'can / will', difficulty: 1 },
    { char: '回', pinyin: 'huí', zhuyin: 'ㄏㄨㄟˊ', meaning: 'to return', difficulty: 1 },
    { char: '回答', pinyin: 'huídá', zhuyin: 'ㄏㄨㄟˊ ㄉㄚˊ', meaning: 'to answer', difficulty: 2 },
    { char: '護理師', pinyin: 'hùlǐshī', zhuyin: 'ㄏㄨˋ ㄌㄧˇ ㄕ', meaning: 'nurse', difficulty: 3 },
    { char: '火車', pinyin: 'huǒchē', zhuyin: 'ㄏㄨㄛˇ ㄔㄜ', meaning: 'train', difficulty: 2 },
    { char: '活動', pinyin: 'huódòng', zhuyin: 'ㄏㄨㄛˊ ㄉㄨㄥˋ', meaning: 'activity', difficulty: 2 },
    { char: '護士', pinyin: 'hùshì', zhuyin: 'ㄏㄨˋ ㄕˋ', meaning: 'nurse', difficulty: 2 },

    // J
    { char: '雞', pinyin: 'jī', zhuyin: 'ㄐㄧ', meaning: 'chicken', difficulty: 1 },
    { char: '幾', pinyin: 'jǐ', zhuyin: 'ㄐㄧˇ', meaning: 'how many', difficulty: 1 },
    { char: '記', pinyin: 'jì', zhuyin: 'ㄐㄧˋ', meaning: 'to remember', difficulty: 2 },
    { char: '幾點鐘', pinyin: 'jǐdiǎnzhōng', zhuyin: 'ㄐㄧˇ ㄉㄧㄢˇ ㄓㄨㄥ', meaning: 'what time', difficulty: 2 },
    { char: '寄', pinyin: 'jì', zhuyin: 'ㄐㄧˋ', meaning: 'to send (mail)', difficulty: 2 },
    { char: '家', pinyin: 'jiā', zhuyin: 'ㄐㄧㄚ', meaning: 'home / family', difficulty: 1 },
    { char: '夾克', pinyin: 'jiákè', zhuyin: 'ㄐㄧㄚˊ ㄎㄜˋ', meaning: 'jacket', difficulty: 3 },
    { char: '家人', pinyin: 'jiārén', zhuyin: 'ㄐㄧㄚ ㄖㄣˊ', meaning: 'family member', difficulty: 2 },
    { char: '家具', pinyin: 'jiājù', zhuyin: 'ㄐㄧㄚ ㄐㄩˋ', meaning: 'furniture', difficulty: 2 },
    { char: '間', pinyin: 'jiān', zhuyin: 'ㄐㄧㄢ', meaning: 'measure word for rooms', difficulty: 2 },
    { char: '件', pinyin: 'jiàn', zhuyin: 'ㄐㄧㄢˋ', meaning: 'measure word for clothes', difficulty: 2 },
    { char: '見', pinyin: 'jiàn', zhuyin: 'ㄐㄧㄢˋ', meaning: 'to see', difficulty: 1 },
    { char: '簡單', pinyin: 'jiǎndān', zhuyin: 'ㄐㄧㄢˇ ㄉㄢ', meaning: 'simple', difficulty: 2 },
    { char: '講', pinyin: 'jiǎng', zhuyin: 'ㄐㄧㄤˇ', meaning: 'to speak', difficulty: 2 },
    { char: '講話', pinyin: 'jiǎnghuà', zhuyin: 'ㄐㄧㄤˇ ㄏㄨㄚˋ', meaning: 'to speak', difficulty: 2 },
    { char: '健康', pinyin: 'jiànkāng', zhuyin: 'ㄐㄧㄢˋ ㄎㄤ', meaning: 'healthy', difficulty: 2 },
    { char: '見面', pinyin: 'jiànmiàn', zhuyin: 'ㄐㄧㄢˋ ㄇㄧㄢˋ', meaning: 'to meet', difficulty: 2 },
    { char: '教', pinyin: 'jiāo', zhuyin: 'ㄐㄧㄠ', meaning: 'to teach', difficulty: 2 },
    { char: '叫', pinyin: 'jiào', zhuyin: 'ㄐㄧㄠˋ', meaning: 'to call', difficulty: 1 },
    { char: '教室', pinyin: 'jiàoshì', zhuyin: 'ㄐㄧㄠˋ ㄕˋ', meaning: 'classroom', difficulty: 2 },
    { char: '腳踏車', pinyin: 'jiǎotàchē', zhuyin: 'ㄐㄧㄠˇ ㄊㄚˋ ㄔㄜ', meaning: 'bicycle', difficulty: 2 },
    { char: '教堂', pinyin: 'jiàotáng', zhuyin: 'ㄐㄧㄠˋ ㄊㄤˊ', meaning: 'church', difficulty: 3 },
    { char: '交通', pinyin: 'jiāotōng', zhuyin: 'ㄐㄧㄠ ㄊㄨㄥ', meaning: 'traffic / transportation', difficulty: 3 },
    { char: '餃子', pinyin: 'jiǎozi', zhuyin: 'ㄐㄧㄠˇ ㄗ˙', meaning: 'dumplings', difficulty: 2 },
    { char: '機場', pinyin: 'jīchǎng', zhuyin: 'ㄐㄧ ㄔㄤˇ', meaning: 'airport', difficulty: 2 },
    { char: '計程車', pinyin: 'jìchéngchē', zhuyin: 'ㄐㄧˋ ㄔㄥˊ ㄔㄜ', meaning: 'taxi', difficulty: 2 },
    { char: '記得', pinyin: 'jìdé', zhuyin: 'ㄐㄧˋ ㄉㄜˊ', meaning: 'to remember', difficulty: 2 },
    { char: '街', pinyin: 'jiē', zhuyin: 'ㄐㄧㄝ', meaning: 'street', difficulty: 2 },
    { char: '接電話', pinyin: 'jiē diànhuà', zhuyin: 'ㄐㄧㄝ ㄉㄧㄢˋ ㄏㄨㄚˋ', meaning: 'to answer the phone', difficulty: 2 },
    { char: '結婚', pinyin: 'jiéhūn', zhuyin: 'ㄐㄧㄝˊ ㄏㄨㄣ', meaning: 'to marry', difficulty: 3 },
    { char: '姐姐', pinyin: 'jiějie', zhuyin: 'ㄐㄧㄝˇ ㄐㄧㄝ˙', meaning: 'older sister', difficulty: 1 },
    { char: '節目', pinyin: 'jiémù', zhuyin: 'ㄐㄧㄝˊ ㄇㄨˋ', meaning: 'program', difficulty: 2 },
    { char: '介紹', pinyin: 'jièshào', zhuyin: 'ㄐㄧㄝˋ ㄕㄠˋ', meaning: 'to introduce', difficulty: 2 },
    { char: '捷運', pinyin: 'jiéyùn', zhuyin: 'ㄐㄧㄝˊ ㄩㄣˋ', meaning: 'MRT / subway', difficulty: 2 },
    { char: '計畫', pinyin: 'jìhuà', zhuyin: 'ㄐㄧˋ ㄏㄨㄚˋ', meaning: 'plan', difficulty: 3 },
    { char: '機會', pinyin: 'jīhuì', zhuyin: 'ㄐㄧ ㄏㄨㄟˋ', meaning: 'chance', difficulty: 2 },
    { char: '斤', pinyin: 'jīn', zhuyin: 'ㄐㄧㄣ', meaning: 'catty (0.6kg)', difficulty: 2 },
    { char: '近', pinyin: 'jìn', zhuyin: 'ㄐㄧㄣˋ', meaning: 'near', difficulty: 1 },
    { char: '進', pinyin: 'jìn', zhuyin: 'ㄐㄧㄣˋ', meaning: 'to enter', difficulty: 2 },
    { char: '進步', pinyin: 'jìnbù', zhuyin: 'ㄐㄧㄣˋ ㄅㄨˋ', meaning: 'to improve', difficulty: 3 },
    { char: '警察', pinyin: 'jǐngchá', zhuyin: 'ㄐㄧㄥˇ ㄔㄚˊ', meaning: 'police', difficulty: 2 },
    { char: '經驗', pinyin: 'jīngyàn', zhuyin: 'ㄐㄧㄥ ㄧㄢˋ', meaning: 'experience', difficulty: 3 },
    { char: '進來', pinyin: 'jìnmái', zhuyin: 'ㄐㄧㄣˋ ㄌㄞˊ', meaning: 'to come in', difficulty: 2 },
    { char: '今年', pinyin: 'jīnnián', zhuyin: 'ㄐㄧㄣ ㄋㄧㄢˊ', meaning: 'this year', difficulty: 2 },
    { char: '進去', pinyin: 'jìnqù', zhuyin: 'ㄐㄧㄣˋ ㄑㄩˋ', meaning: 'to go in', difficulty: 2 },
    { char: '今天', pinyin: 'jīntiān', zhuyin: 'ㄐㄧㄣ ㄊㄧㄢ', meaning: 'today', difficulty: 1 },
    { char: '緊張', pinyin: 'jǐnzhāng', zhuyin: 'ㄐㄧㄣˇ ㄓㄤ', meaning: 'nervous', difficulty: 2 },
    { char: '九', pinyin: 'jiǔ', zhuyin: 'ㄐㄧㄡˇ', meaning: 'nine', difficulty: 1 },
    { char: '酒', pinyin: 'jiǔ', zhuyin: 'ㄐㄧㄡˇ', meaning: 'alcohol', difficulty: 2 },
    { char: '久', pinyin: 'jiǔ', zhuyin: 'ㄐㄧㄡˇ', meaning: 'long time', difficulty: 2 },
    { char: '舊', pinyin: 'jiù', zhuyin: 'ㄐㄧㄡˋ', meaning: 'old', difficulty: 2 },
    { char: '就', pinyin: 'jiù', zhuyin: 'ㄐㄧㄡˋ', meaning: 'then', difficulty: 1 },
    { char: '記者', pinyin: 'jìzhě', zhuyin: 'ㄐㄧˋ ㄓㄜˇ', meaning: 'reporter', difficulty: 3 },
    { char: '覺得', pinyin: 'juédé', zhuyin: 'ㄐㄩㄝˊ ㄉㄜ˙', meaning: 'to feel / think', difficulty: 1 },
    { char: '決定', pinyin: 'juédìng', zhuyin: 'ㄐㄩㄝˊ ㄉㄧㄥˋ', meaning: 'to decide', difficulty: 2 },
    { char: '句子', pinyin: 'jùzi', zhuyin: 'ㄐㄩˋ ㄗ˙', meaning: 'sentence', difficulty: 2 },

    // K
    { char: '咖啡', pinyin: 'kāfēi', zhuyin: 'ㄎㄚ ㄈㄟ', meaning: 'coffee', difficulty: 1 },
    { char: '咖啡廳', pinyin: 'kāfēitīng', zhuyin: 'ㄎㄚ ㄈㄟ ㄊㄧㄥ', meaning: 'cafe', difficulty: 2 },
    { char: '開', pinyin: 'kāi', zhuyin: 'ㄎㄞ', meaning: 'to open', difficulty: 1 },
    { char: '開車', pinyin: 'kāichē', zhuyin: 'ㄎㄞ ㄔㄜ', meaning: 'to drive', difficulty: 2 },
    { char: '開始', pinyin: 'kāishǐ', zhuyin: 'ㄎㄞ ㄕˇ', meaning: 'to start', difficulty: 2 },
    { char: '開心', pinyin: 'kāixīn', zhuyin: 'ㄎㄞ ㄒㄧㄣ', meaning: 'happy', difficulty: 2 },
    { char: '看', pinyin: 'kàn', zhuyin: 'ㄎㄢˋ', meaning: 'to look', difficulty: 1 },
    { char: '看到', pinyin: 'kàndào', zhuyin: 'ㄎㄢˋ ㄉㄠˋ', meaning: 'to see', difficulty: 2 },
    { char: '考', pinyin: 'kǎo', zhuyin: 'ㄎㄠˇ', meaning: 'to test', difficulty: 2 },
    { char: '考試', pinyin: 'kǎoshì', zhuyin: 'ㄎㄠˇ ㄕˋ', meaning: 'exam', difficulty: 2 },
    { char: '卡片', pinyin: 'kǎpiàn', zhuyin: 'ㄎㄚˇ ㄆㄧㄢˋ', meaning: 'card', difficulty: 2 },
    { char: '棵', pinyin: 'kē', zhuyin: 'ㄎㄜ', meaning: 'measure word for trees', difficulty: 2 },
    { char: '渴', pinyin: 'kě', zhuyin: 'ㄎㄜˇ', meaning: 'thirsty', difficulty: 2 },
    { char: '課', pinyin: 'kè', zhuyin: 'ㄎㄜˋ', meaning: 'class', difficulty: 1 },
    { char: '可愛', pinyin: 'kě’ài', zhuyin: 'ㄎㄜˇ ㄞˋ', meaning: 'cute', difficulty: 2 },
    { char: '課本', pinyin: 'kèběn', zhuyin: 'ㄎㄜˋ ㄅㄣˇ', meaning: 'textbook', difficulty: 2 },
    { char: '可能', pinyin: 'kěnéng', zhuyin: 'ㄎㄜˇ ㄋㄥˊ', meaning: 'maybe', difficulty: 2 },
    { char: '可是', pinyin: 'kěshì', zhuyin: 'ㄎㄜˇ ㄕˋ', meaning: 'but', difficulty: 1 },
    { char: '咳嗽', pinyin: 'késòu', zhuyin: 'ㄎㄜˊ ㄙㄡˋ', meaning: 'to cough', difficulty: 3 },
    { char: '客廳', pinyin: 'kètīng', zhuyin: 'ㄎㄜˋ ㄊㄧㄥ', meaning: 'living room', difficulty: 2 },
    { char: '科學', pinyin: 'kēxué', zhuyin: 'ㄎㄜ ㄒㄩㄝˊ', meaning: 'science', difficulty: 2 },
    { char: '課文', pinyin: 'kèwén', zhuyin: 'ㄎㄜˋ ㄨㄣˊ', meaning: 'text (of a lesson)', difficulty: 3 },
    { char: '可以', pinyin: 'kěyǐ', zhuyin: 'ㄎㄜˇ ㄧˇ', meaning: 'can', difficulty: 1 },
    { char: '口罩', pinyin: 'kǒuzhào', zhuyin: 'ㄎㄡˇ ㄓㄠˋ', meaning: 'mask', difficulty: 2 },
    { char: '快', pinyin: 'kuài', zhuyin: 'ㄎㄨㄞˋ', meaning: 'fast', difficulty: 1 },
    { char: '塊', pinyin: 'kuài', zhuyin: 'ㄎㄨㄞˋ', meaning: 'piece / dollar', difficulty: 1 },
    { char: '快樂', pinyin: 'kuàilè', zhuyin: 'ㄎㄨㄞˋ ㄌㄜˋ', meaning: 'happy', difficulty: 2 },
    { char: '快要', pinyin: 'kuàiyào', zhuyin: 'ㄎㄨㄞˋ ㄧㄠˋ', meaning: 'about to / soon', difficulty: 2 },
    { char: '跨年', pinyin: 'kuànián', zhuyin: 'ㄎㄨㄚˋ ㄋㄧㄢˊ', meaning: 'to celebrate New Year\'s Eve', difficulty: 3 },
    { char: '褲子', pinyin: 'kùzi', zhuyin: 'ㄎㄨˋ ㄗ˙', meaning: 'pants', difficulty: 2 },

    // L
    { char: '來', pinyin: 'lái', zhuyin: 'ㄌㄞˊ', meaning: 'to come', difficulty: 1 },
    { char: '藍', pinyin: 'lán', zhuyin: 'ㄌㄢˊ', meaning: 'blue', difficulty: 1 },
    { char: '籃球', pinyin: 'lánqiú', zhuyin: 'ㄌㄢˊ ㄑㄧㄡˊ', meaning: 'basketball', difficulty: 2 },
    { char: '藍色', pinyin: 'lánsè', zhuyin: 'ㄌㄢˊ ㄙㄜˋ', meaning: 'blue color', difficulty: 2 },
    { char: '老', pinyin: 'lǎo', zhuyin: 'ㄌㄠˇ', meaning: 'old', difficulty: 1 },
    { char: '老闆', pinyin: 'lǎobǎn', zhuyin: 'ㄌㄠˇ ㄅㄢˇ', meaning: 'boss', difficulty: 2 },
    { char: '老師', pinyin: 'lǎoshī', zhuyin: 'ㄌㄠˇ ㄕ', meaning: 'teacher', difficulty: 1 },
    { char: '了', pinyin: 'le', zhuyin: 'ㄌㄜ˙', meaning: 'particle', difficulty: 1 },
    { char: '累', pinyin: 'lèi', zhuyin: 'ㄌㄟˋ', meaning: 'tired', difficulty: 1 },
    { char: '冷', pinyin: 'lěng', zhuyin: 'ㄌㄥˇ', meaning: 'cold', difficulty: 1 },
    { char: '冷氣', pinyin: 'lěngqì', zhuyin: 'ㄌㄥˇ ㄑㄧˋ', meaning: 'air conditioning', difficulty: 2 },
    { char: '離', pinyin: 'lí', zhuyin: 'ㄌㄧˊ', meaning: 'away from', difficulty: 2 },
    { char: '裡', pinyin: 'lǐ', zhuyin: 'ㄌㄧˇ', meaning: 'inside', difficulty: 1 },
    { char: '臉', pinyin: 'liǎn', zhuyin: 'ㄌㄧㄢˇ', meaning: 'face', difficulty: 2 },
    { char: '兩', pinyin: 'liǎng', zhuyin: 'ㄌㄧㄤˇ', meaning: 'two', difficulty: 1 },
    { char: '輛', pinyin: 'liàng', zhuyin: 'ㄌㄧㄤˋ', meaning: 'measure word for vehicles', difficulty: 2 },
    { char: '練習', pinyin: 'liànxí', zhuyin: 'ㄌㄧㄢˋ ㄒㄧˊ', meaning: 'to practice', difficulty: 2 },
    { char: '涼快', pinyin: 'liángkuài', zhuyin: 'ㄌㄧㄤˊ ㄎㄨㄞˋ', meaning: 'cool', difficulty: 2 },
    { char: '聊天', pinyin: 'liáotiān', zhuyin: 'ㄌㄧㄠˊ ㄊㄧㄢ', meaning: 'to chat', difficulty: 2 },
    { char: '了解', pinyin: 'liǎojiě', zhuyin: 'ㄌㄧㄠˇ ㄐㄧㄝˇ', meaning: 'to understand', difficulty: 3 },
    { char: '零', pinyin: 'líng', zhuyin: 'ㄌㄧㄥˊ', meaning: 'zero', difficulty: 1 },
    { char: '歷史', pinyin: 'lìshǐ', zhuyin: 'ㄌㄧˋ ㄕˇ', meaning: 'history', difficulty: 3 },
    { char: '六', pinyin: 'liù', zhuyin: 'ㄌㄧㄡˋ', meaning: 'six', difficulty: 1 },
    { char: '流行', pinyin: 'liúxíng', zhuyin: 'ㄌㄧㄡˊ ㄒㄧㄥˊ', meaning: 'popular', difficulty: 2 },
    { char: '留言', pinyin: 'liúyán', zhuyin: 'ㄌㄧㄡˊ ㄧㄢˊ', meaning: 'to leave a message', difficulty: 2 },
    { char: '禮物', pinyin: 'lǐwù', zhuyin: 'ㄌㄧˇ ㄨˋ', meaning: 'gift', difficulty: 2 },
    { char: '龍', pinyin: 'lóng', zhuyin: 'ㄌㄨㄥˊ', meaning: 'dragon', difficulty: 2 },
    { char: '樓', pinyin: 'lóu', zhuyin: 'ㄌㄡˊ', meaning: 'floor', difficulty: 2 },
    { char: '樓上', pinyin: 'lóushàng', zhuyin: 'ㄌㄡˊ ㄕㄤˋ', meaning: 'upstairs', difficulty: 2 },
    { char: '樓梯', pinyin: 'lóutī', zhuyin: 'ㄌㄡˊ ㄊㄧ', meaning: 'stairs', difficulty: 2 },
    { char: '樓下', pinyin: 'lóuxià', zhuyin: 'ㄌㄡˊ ㄒㄧㄚˋ', meaning: 'downstairs', difficulty: 2 },
    { char: '路', pinyin: 'lù', zhuyin: 'ㄌㄨˋ', meaning: 'road', difficulty: 1 },
    { char: '綠茶', pinyin: 'lǜchá', zhuyin: 'ㄌㄩˋ ㄔㄚˊ', meaning: 'green tea', difficulty: 2 },
    { char: '旅館', pinyin: 'lǚguǎn', zhuyin: 'ㄌㄩˇ ㄍㄨㄢˇ', meaning: 'hotel', difficulty: 2 },
    { char: '路口', pinyin: 'lùkǒu', zhuyin: 'ㄌㄨˋ ㄎㄡˇ', meaning: 'intersection', difficulty: 2 },
    { char: '綠色', pinyin: 'lǜsè', zhuyin: 'ㄌㄩˋ ㄙㄜˋ', meaning: 'green color', difficulty: 2 },
    { char: '旅行', pinyin: 'lǚxíng', zhuyin: 'ㄌㄩˇ ㄒㄧㄥˊ', meaning: 'travel', difficulty: 2 },

    // M
    { char: '媽媽', pinyin: 'māma', zhuyin: 'ㄇㄚ ㄇㄚ˙', meaning: 'mother', difficulty: 1 },
    { char: '慢', pinyin: 'màn', zhuyin: 'ㄇㄢˋ', meaning: 'slow', difficulty: 1 },
    { char: '忙', pinyin: 'máng', zhuyin: 'ㄇㄤˊ', meaning: 'busy', difficulty: 1 },
    { char: '貓', pinyin: 'māo', zhuyin: 'ㄇㄠ', meaning: 'cat', difficulty: 1 },
    { char: '毛筆', pinyin: 'máobǐ', zhuyin: 'ㄇㄠˊ ㄅㄧˇ', meaning: 'brush pen', difficulty: 3 },
    { char: '馬上', pinyin: 'mǎshàng', zhuyin: 'ㄇㄚˇ ㄕㄤˋ', meaning: 'immediately', difficulty: 2 },
    { char: '沒', pinyin: 'méi', zhuyin: 'ㄇㄟˊ', meaning: 'not', difficulty: 1 },
    { char: '每', pinyin: 'měi', zhuyin: 'ㄇㄟˇ', meaning: 'every', difficulty: 1 },
    { char: '沒問題', pinyin: 'méi wèntí', zhuyin: 'ㄇㄟˊ ㄨㄣˋ ㄊㄧˊ', meaning: 'no problem', difficulty: 2 },
    { char: '沒關係', pinyin: 'méiguānxì', zhuyin: 'ㄇㄟˊ ㄍㄨㄢ ㄒㄧ˙', meaning: 'it\'s okay', difficulty: 2 },
    { char: '美國', pinyin: 'Měiguó', zhuyin: 'ㄇㄟˇ ㄍㄨㄛˊ', meaning: 'USA', difficulty: 2 },
    { char: '沒空', pinyin: 'méikòng', zhuyin: 'ㄇㄟˊ ㄎㄨㄥˋ', meaning: 'no time', difficulty: 2 },
    { char: '妹妹', pinyin: 'mèimei', zhuyin: 'ㄇㄟˋ ㄇㄟ˙', meaning: 'younger sister', difficulty: 1 },
    { char: '門', pinyin: 'mén', zhuyin: 'ㄇㄣˊ', meaning: 'door', difficulty: 1 },
    { char: '門口', pinyin: 'ménkǒu', zhuyin: 'ㄇㄣˊ ㄎㄡˇ', meaning: 'doorway', difficulty: 2 },
    { char: '麵', pinyin: 'miàn', zhuyin: 'ㄇㄧㄢˋ', meaning: 'noodles', difficulty: 2 },
    { char: '麵包', pinyin: 'miànbāo', zhuyin: 'ㄇㄧㄢˋ ㄅㄠ', meaning: 'bread', difficulty: 2 },
    { char: '明年', pinyin: 'míngnián', zhuyin: 'ㄇㄧㄥˊ ㄋㄧㄢˊ', meaning: 'next year', difficulty: 2 },
    { char: '明天', pinyin: 'míngtiān', zhuyin: 'ㄇㄧㄥˊ ㄊㄧㄢ', meaning: 'tomorrow', difficulty: 1 },
    { char: '明天見', pinyin: 'míngtiān jiàn', zhuyin: 'ㄇㄧㄥˊ ㄊㄧㄢ ㄐㄧㄢˋ', meaning: 'see you tomorrow', difficulty: 2 },
    { char: '名字', pinyin: 'míngzì', zhuyin: 'ㄇㄧㄥˊ ㄗ˙', meaning: 'name', difficulty: 2 },
    { char: '母親', pinyin: 'mǔqīn', zhuyin: 'ㄇㄨˇ ㄑㄧㄣ', meaning: 'mother (formal)', difficulty: 3 },

    // N
    { char: '那', pinyin: 'nà', zhuyin: 'ㄋㄚˋ', meaning: 'that', difficulty: 1 },
    { char: '拿', pinyin: 'ná', zhuyin: 'ㄋㄚˊ', meaning: 'to take', difficulty: 2 },
    { char: '哪', pinyin: 'nǎ', zhuyin: 'ㄋㄚˇ', meaning: 'which', difficulty: 1 },
    { char: '奶茶', pinyin: 'nǎichá', zhuyin: 'ㄋㄞˇ ㄔㄚˊ', meaning: 'milk tea', difficulty: 2 },
    { char: '哪裡', pinyin: 'nǎlǐ', zhuyin: 'ㄋㄚˇ ㄌㄧˇ', meaning: 'where', difficulty: 1 },
    { char: '那裡', pinyin: 'nàlǐ', zhuyin: 'ㄋㄚˋ ㄌㄧˇ', meaning: 'there', difficulty: 1 },
    { char: '那麼', pinyin: 'nàme', zhuyin: 'ㄋㄚˋ ㄇㄜ˙', meaning: 'so / that', difficulty: 2 },
    { char: '難', pinyin: 'nán', zhuyin: 'ㄋㄢˊ', meaning: 'difficult', difficulty: 2 },
    { char: '南', pinyin: 'nán', zhuyin: 'ㄋㄢˊ', meaning: 'south', difficulty: 2 },
    { char: '男', pinyin: 'nán', zhuyin: 'ㄋㄢˊ', meaning: 'male', difficulty: 1 },
    { char: '男生', pinyin: 'nánshēng', zhuyin: 'ㄋㄢˊ ㄕㄥ', meaning: 'boy', difficulty: 2 },
    { char: '那些', pinyin: 'nàxiē', zhuyin: 'ㄋㄚˋ ㄒㄧㄝ', meaning: 'those', difficulty: 2 },
    { char: '呢', pinyin: 'ne', zhuyin: 'ㄋㄜ˙', meaning: 'particle', difficulty: 1 },
    { char: '能', pinyin: 'néng', zhuyin: 'ㄋㄥˊ', meaning: 'can', difficulty: 2 },
    { char: '你', pinyin: 'nǐ', zhuyin: 'ㄋㄧˇ', meaning: 'you', difficulty: 1 },
    { char: '妳', pinyin: 'nǐ', zhuyin: 'ㄋㄧˇ', meaning: 'you (female)', difficulty: 1 },
    { char: '年', pinyin: 'nián', zhuyin: 'ㄋㄧㄢˊ', meaning: 'year', difficulty: 1 },
    { char: '年級', pinyin: 'niánjí', zhuyin: 'ㄋㄧㄢˊ ㄐㄧˊ', meaning: 'grade / year', difficulty: 2 },
    { char: '年輕', pinyin: 'niánqīng', zhuyin: 'ㄋㄧㄢˊ ㄑㄧㄥ', meaning: 'young', difficulty: 2 },
    { char: '鳥', pinyin: 'niǎo', zhuyin: 'ㄋㄧㄠˇ', meaning: 'bird', difficulty: 1 },
    { char: '你好', pinyin: 'nǐhǎo', zhuyin: 'ㄋㄧˇ ㄏㄠˇ', meaning: 'hello', difficulty: 1 },
    { char: '你們', pinyin: 'nǐmen', zhuyin: 'ㄋㄧˇ ㄇㄣ˙', meaning: 'you (plural)', difficulty: 1 },
    { char: '您', pinyin: 'nín', zhuyin: 'ㄋㄧㄣˊ', meaning: 'you (polite)', difficulty: 2 },
    { char: '牛', pinyin: 'niú', zhuyin: 'ㄋㄧㄡˊ', meaning: 'cow', difficulty: 1 },
    { char: '牛奶', pinyin: 'niúnǎi', zhuyin: 'ㄋㄧㄡˊ ㄋㄞˇ', meaning: 'milk', difficulty: 2 },
    { char: '牛肉', pinyin: 'niúròu', zhuyin: 'ㄋㄧㄡˊ ㄖㄡˋ', meaning: 'beef', difficulty: 2 },
    { char: '牛肉麵', pinyin: 'niúròumiàn', zhuyin: 'ㄋㄧㄡˊ ㄖㄡˋ ㄇㄧㄢˋ', meaning: 'beef noodles', difficulty: 2 },
    { char: '女', pinyin: 'nǚ', zhuyin: 'ㄋㄩˇ', meaning: 'female', difficulty: 1 },
    { char: '女兒', pinyin: 'nǚ\'ér', zhuyin: 'ㄋㄩˇ ㄦˊ', meaning: 'daughter', difficulty: 2 },
    { char: '女生', pinyin: 'nǚshēng', zhuyin: 'ㄋㄩˇ ㄕㄥ', meaning: 'girl', difficulty: 2 },

    // P
    { char: '怕', pinyin: 'pà', zhuyin: 'ㄆㄚˋ', meaning: 'to be afraid', difficulty: 2 },
    { char: '排', pinyin: 'pái', zhuyin: 'ㄆㄞˊ', meaning: 'to arrange', difficulty: 2 },
    { char: '排隊', pinyin: 'páiduì', zhuyin: 'ㄆㄞˊ ㄉㄨㄟˋ', meaning: 'to queue', difficulty: 2 },
    { char: '盤子', pinyin: 'pánzi', zhuyin: 'ㄆㄢˊ ㄗ˙', meaning: 'plate', difficulty: 2 },
    { char: '胖', pinyin: 'pàng', zhuyin: 'ㄆㄤˋ', meaning: 'fat', difficulty: 2 },
    { char: '旁邊', pinyin: 'pángbiān', zhuyin: 'ㄆㄤˊ ㄅㄧㄢ', meaning: 'beside', difficulty: 2 },
    { char: '跑', pinyin: 'pǎo', zhuyin: 'ㄆㄠˇ', meaning: 'to run', difficulty: 2 },
    { char: '跑步', pinyin: 'pǎobù', zhuyin: 'ㄆㄠˇ ㄅㄨˋ', meaning: 'to run', difficulty: 2 },
    { char: '朋友', pinyin: 'péngyǒu', zhuyin: 'ㄆㄥˊ ㄧㄡˇ', meaning: 'friend', difficulty: 1 },
    { char: '便宜', pinyin: 'piányí', zhuyin: 'ㄆㄧㄢˊ ㄧˊ', meaning: 'cheap', difficulty: 2 },
    { char: '票', pinyin: 'piào', zhuyin: 'ㄆㄧㄠˋ', meaning: 'ticket', difficulty: 2 },
    { char: '漂亮', pinyin: 'piàoliàng', zhuyin: 'ㄆㄧㄠˋ ㄌㄧㄤˋ', meaning: 'beautiful', difficulty: 1 },
    { char: '皮包', pinyin: 'píbāo', zhuyin: 'ㄆㄧˊ ㄅㄠ', meaning: 'purse', difficulty: 2 },
    { char: '瓶', pinyin: 'píng', zhuyin: 'ㄆㄧㄥˊ', meaning: 'bottle', difficulty: 2 },
    { char: '平常', pinyin: 'píngcháng', zhuyin: 'ㄆㄧㄥˊ ㄔㄤˊ', meaning: 'usually', difficulty: 2 },
    { char: '蘋果', pinyin: 'píngguǒ', zhuyin: 'ㄆㄧㄥˊ ㄍㄨㄛˇ', meaning: 'apple', difficulty: 1 },
    { char: '瓶子', pinyin: 'píngzi', zhuyin: 'ㄆㄧㄥˊ ㄗ˙', meaning: 'bottle', difficulty: 2 },

    // Q
    { char: '七', pinyin: 'qī', zhuyin: 'ㄑㄧ', meaning: 'seven', difficulty: 1 },
    { char: '騎', pinyin: 'qí', zhuyin: 'ㄑㄧˊ', meaning: 'to ride', difficulty: 2 },
    { char: '千', pinyin: 'qiān', zhuyin: 'ㄑㄧㄢ', meaning: 'thousand', difficulty: 2 },
    { char: '錢', pinyin: 'qián', zhuyin: 'ㄑㄧㄢˊ', meaning: 'money', difficulty: 1 },
    { char: '前', pinyin: 'qián', zhuyin: 'ㄑㄧㄢˊ', meaning: 'before', difficulty: 1 },
    { char: '前面', pinyin: 'qiánmiàn', zhuyin: 'ㄑㄧㄢˊ ㄇㄧㄢˋ', meaning: 'front', difficulty: 1 },
    { char: '錢包', pinyin: 'qiánbāo', zhuyin: 'ㄑㄧㄢˊ ㄅㄠ', meaning: 'wallet', difficulty: 2 },
    { char: '鉛筆', pinyin: 'qiānbǐ', zhuyin: 'ㄑㄧㄢ ㄅㄧˇ', meaning: 'pencil', difficulty: 2 },
    { char: '前天', pinyin: 'qiántiān', zhuyin: 'ㄑㄧㄢˊ ㄊㄧㄢ', meaning: 'day before yesterday', difficulty: 2 },
    { char: '巧克力', pinyin: 'qiǎokèlì', zhuyin: 'ㄑㄧㄠˇ ㄎㄜˋ ㄌㄧˋ', meaning: 'chocolate', difficulty: 2 },
    { char: '汽車', pinyin: 'qìchē', zhuyin: 'ㄑㄧˋ ㄔㄜ', meaning: 'car', difficulty: 2 },
    { char: '起床', pinyin: 'qǐchuáng', zhuyin: 'ㄑㄧˇ ㄔㄨㄤˊ', meaning: 'to get up', difficulty: 2 },
    { char: '起飛', pinyin: 'qǐfēi', zhuyin: 'ㄑㄧˇ ㄈㄟ', meaning: 'to take off', difficulty: 2 },
    { char: '奇怪', pinyin: 'qíguài', zhuyin: 'ㄑㄧˊ ㄍㄨㄞˋ', meaning: 'strange', difficulty: 3 },
    { char: '請', pinyin: 'qǐng', zhuyin: 'ㄑㄧㄥˇ', meaning: 'please', difficulty: 1 },
    { char: '請假', pinyin: 'qǐngjià', zhuyin: 'ㄑㄧㄥˇ ㄐㄧㄚˋ', meaning: 'to ask for leave', difficulty: 3 },
    { char: '請問', pinyin: 'qǐngwèn', zhuyin: 'ㄑㄧㄥˇ ㄨㄣˋ', meaning: 'excuse me', difficulty: 1 },
    { char: '慶祝', pinyin: 'qìngzhù', zhuyin: 'ㄑㄧㄥˋ ㄓㄨˋ', meaning: 'to celebrate', difficulty: 3 },
    { char: '其他', pinyin: 'qítā', zhuyin: 'ㄑㄧˊ ㄊㄚ', meaning: 'other', difficulty: 2 },
    { char: '秋天', pinyin: 'qiūtiān', zhuyin: 'ㄑㄧㄡ ㄊㄧㄢ', meaning: 'autumn', difficulty: 2 },
    { char: '球', pinyin: 'qiú', zhuyin: 'ㄑㄧㄡˊ', meaning: 'ball', difficulty: 1 },
    { char: '期中考', pinyin: 'qīzhōngkǎo', zhuyin: 'ㄑㄧ ㄓㄨㄥ ㄎㄠˇ', meaning: 'midterm exam', difficulty: 3 },
    { char: '去', pinyin: 'qù', zhuyin: 'ㄑㄩˋ', meaning: 'to go', difficulty: 1 },
    { char: '去年', pinyin: 'qùnián', zhuyin: 'ㄑㄩˋ ㄋㄧㄢˊ', meaning: 'last year', difficulty: 2 },
    { char: '裙子', pinyin: 'qúnzi', zhuyin: 'ㄑㄩㄣˊ ㄗ˙', meaning: 'skirt', difficulty: 2 },
];


