export const EXAMPLES = {
    // Homework 1
    '吃': { s: '我喜歡吃水果。', t: 'I like to eat fruit.' },
    '愛': { s: '媽媽愛我。', t: 'Mom loves me.' },
    '友': { s: '他是我的好朋友。', t: 'He is my good friend.' },
    '朋': { s: '我有許多朋友。', t: 'I have many friends.' },
    '家': { s: '我的家很大。', t: 'My home is big.' },
    '大': { s: '這隻狗很大。', t: 'This dog is big.' },
    '氣': { s: '今天天氣很好。', t: 'The weather is good today.' },
    '客': { s: '家裡有客人。', t: 'There are guests at home.' },
    '謝': { s: '謝謝你的幫忙。', t: 'Thank you for your help.' },
    '喝': { s: '我想喝水。', t: 'I want to drink water.' },
    '果': { s: '桌上有水果。', t: 'There is fruit on the table.' },
    '水': { s: '請給我一杯水。', t: 'Please give me a glass of water.' },
    '珠': { s: '這是珍珠奶茶。', t: 'This is bubble tea.' },
    '珍': { s: '珍珠很貴。', t: 'Pearls are expensive.' },
    '紹': { s: '請自我介紹。', t: 'Please introduce yourself.' },
    '介': { s: '我介紹朋友給你。', t: 'I introduce a friend to you.' },
    '我': { s: '我是學生。', t: 'I am a student.' },
    '自': { s: '我自己去。', t: 'I go by myself.' },
    '茶': { s: '爸爸喜歡喝茶。', t: 'Dad likes to drink tea.' },
    '奶': { s: '我不喝牛奶。', t: 'I do not drink milk.' },

    // Homework 2
    '呢': { s: '你呢？', t: 'How about you?' },
    '姓': { s: '我也姓王。', t: 'My surname is also Wang.' },
    '字': { s: '這是一個中文字。', t: 'This is a Chinese character.' },
    '名': { s: '你的名字是什麼？', t: 'What is your name?' },
    '麼': { s: '你在做什麼？', t: 'What are you doing?' },
    '什': { s: '那是什麼？', t: 'What is that?' },
    '好': { s: '你好嗎？', t: 'How are you?' },
    '妳': { s: '妳好漂亮。', t: 'You are beautiful.' },
    '歡': { s: '歡迎光臨。', t: 'Welcome.' },
    '喜': { s: '我喜歡你。', t: 'I like you.' },
    '尼': { s: '尼加拉瓜在哪裡？', t: 'Where is Nicaragua?' },
    '印': { s: '這是印尼菜。', t: 'This is Indonesian food.' },
    '媽': { s: '媽媽在煮飯。', t: 'Mom is cooking.' },
    '爸': { s: '爸爸在上班。', t: 'Dad is working.' },
    '問': { s: '我可以問一個問題嗎？', t: 'Can I ask a question?' },
    '請': { s: '請坐。', t: 'Please sit down.' },

    // Homework 3 (Mostly overlapped)

    // Homework 4
    '去': { s: '我們去公園吧。', t: 'Let\'s go to the park.' },
    '在': { s: '我在家。', t: 'I am at home.' },
    '現': { s: '現在幾點？', t: 'What time is it now?' },
    '鐘': { s: '還有五分鐘。', t: 'Five minutes left.' },
    '點': { s: '現在三點。', t: 'It is three o\'clock.' },
    '幾': { s: '你有幾本書？', t: 'How many books do you have?' },
    '子': { s: '這是我的兒子。', t: 'This is my son.' },
    '孩': { s: '那個孩子很可愛。', t: 'That child is cute.' },
    '校': { s: '我去學校上課。', t: 'I go to school for class.' },
    '學': { s: '我學習中文。', t: 'I learn Chinese.' },
    '號': { s: '今天是幾號？', t: 'What is the date today?' },
    '月': { s: '現在是五月。', t: 'It is May now.' },
    '期': { s: '星期日不用上課。', t: 'No class on Sunday.' },
    '星': { s: '天上有很多星星。', t: 'There are many stars in the sky.' },
    '天': { s: '今天天氣很好。', t: 'Also: Today\'s weather is good.' },
    '今': { s: '今天我很忙。', t: 'I am busy today.' },
    '課': { s: '我們在上課。', t: 'We are in class.' },
    '沒': { s: '我沒有錢。', t: 'I don\'t have money.' },
    '有': { s: '我有兩個哥哥。', t: 'I have two older brothers.' },
    '上': { s: '貓在桌子上。', t: 'The cat is on the table.' },
    '早': { s: '早安！', t: 'Good morning!' },
    '日': { s: '今天是星期日。', t: 'Today is Sunday.' },
    '回': { s: '我回家了。', t: 'I went home.' },
    '午': { s: '我們吃午餐。', t: 'We eat lunch.' },
    '中': { s: '我在學中文。', t: 'I am learning Chinese.' },
    '館': { s: '我們去圖書館。', t: 'We go to the library.' },
    '書': { s: '這是一本書。', t: 'This is a book.' },
    '圖': { s: '圖書館有很多書。', t: 'The library has many books.' },
    '機': { s: '這是我的手機。', t: 'This is my mobile phone.' },
    '手': { s: '請洗手。', t: 'Please wash your hands.' },
    '分': { s: '現在十點十分。', t: 'It is 10:10.' },
    '下': { s: '我們下課了。', t: 'Class is dismissed.' },
    '人': { s: '這裡很多人。', t: 'There are many people here.' },
    '做': { s: '你在做什麼？', t: 'What are you doing?' },
    '歲': { s: '你幾歲？', t: 'How old are you?' },
    '起': { s: '我七點起床。', t: 'I get up at seven.' },
    '床': { s: '這張床很大。', t: 'This bed is big.' },
    '晚': { s: '晚安。', t: 'Good night.' },
    '飯': { s: '我們一起吃飯。', t: 'Let\'s eat together.' },
    '睡': { s: '我想睡覺。', t: 'I want to sleep.' },
    '覺': { s: '他在睡覺。', t: 'He is sleeping.' },
    '忙': { s: '爸爸工作很忙。', t: 'Dad is busy with work.' },
    '累': { s: '我很累。', t: 'I am tired.' },

    // Worksheet 6 / Test 4 (Already covered partly)
    '個': { s: '一個蘋果。', t: 'One apple.' },
    '送': { s: '媽媽送我去學校。', t: 'Mom takes me to school.' },
    '想': { s: '我想喝咖啡。', t: 'I want to drink coffee.' },
    '物': { s: '這是我送給你的禮物', t: 'This is the gift I gave you.' },
    '禮': { s: '生日禮物。', t: 'Birthday gift.' },
    '買': { s: '我要買東西。', t: 'I want to buy something.' },
    '文': { s: '英文很難。', t: 'English is hard.' },
    '本': { s: '一本書。', t: 'A book.' },
    '兩': { s: '兩個人。', t: 'Two people.' },
    '看': { s: '看書。', t: 'Reading a book.' },
    '和': { s: '我和你。', t: 'You and me.' },
    '朵': { s: '一朵花。', t: 'A flower.' },
    '花': { s: '花開了。', t: 'The flowers bloomed.' },
    '些': { s: '一些人。', t: 'Some people.' },
    '一': { s: '第一名。', t: 'First place.' },
    '英': { s: '英國。', t: 'UK.' },
    '啊': { s: '是啊！', t: 'Yes indeed!' },
    '糕': { s: '蛋糕。', t: 'Cake.' },
    '蛋': { s: '雞蛋。', t: 'Chicken egg.' },
    '小': { s: '小孩。', t: 'Child.' },

    // HSK1 & Extras
    '二': { s: '二月二日。', t: 'February 2nd.' },
    '三': { s: '三點鐘。', t: 'Three o\'clock.' },
    '口': { s: '一家三口。', t: 'A family of three.' },
    '山': { s: '山上。', t: 'On the mountain.' },
    '四': { s: '四個。', t: 'Four.' },
    '五': { s: '五天。', t: 'Five days.' },
    '六': { s: '星期六。', t: 'Saturday.' },
    '七': { s: '七月。', t: 'July.' },
    '八': { s: '八點。', t: 'Eight o\'clock.' },
    '九': { s: '九個。', t: 'Nine.' },
    '十': { s: '十月。', t: 'October.' },
    '百': { s: '一百元。', t: 'One hundred yuan.' },
    '零': { s: '零度。', t: 'Zero degrees.' },
    '年': { s: '明年。', t: 'Next year.' },
    '時': { s: '時間。', t: 'Time.' },
    '候': { s: '時候。', t: 'Time/Moment.' },
    '半': { s: '兩點半。', t: '2:30.' },
    '你': { s: '你是誰？', t: 'Who are you?' },
    '他': { s: '他是我的老師。', t: 'He is my teacher.' },
    '她': { s: '她很漂亮。', t: 'She is beautiful.' },
    '們': { s: '我們。', t: 'We.' },
    '誰': { s: '那是誰？', t: 'Who is that?' },
    '兒': { s: '兒子。', t: 'Son.' },
    '女': { s: '女兒。', t: 'Daughter.' },
    '老': { s: '老師。', t: 'Teacher.' },
    '師': { s: '老師好。', t: 'Hello teacher.' },
    '同': { s: '同學。', t: 'Classmate.' },
    '先': { s: '先生。', t: 'Mr.' },
    '姐': { s: '小姐。', t: 'Miss.' },
    '是': { s: '這是書。', t: 'This is a book.' },
    '會': { s: '我會說中文。', t: 'I can speak Chinese.' },
    '能': { s: '你能來嗎？', t: 'Can you come?' },
    '要': { s: '我要喝水。', t: 'I want to drink water.' },
    '來': { s: '請過來。', t: 'Please come here.' },
    '聽': { s: '聽音樂。', t: 'Listening to music.' },
    '說': { s: '說話。', t: 'Speaking.' },
    '讀': { s: '讀書。', t: 'Reading.' },
    '寫': { s: '寫字。', t: 'Writing characters.' },
    '工': { s: '工作。', t: 'Work.' },
    '作': { s: '作業。', t: 'Homework.' },
    '住': { s: '你住在哪裡？', t: 'Where do you live?' },
    '坐': { s: '坐下。', t: 'Sit down.' },
    '叫': { s: '我叫小明。', t: 'My name is Xiao Ming.' },
    '打': { s: '打電話。', t: 'Make a phone call.' },
    '開': { s: '開門。', t: 'Open the door.' },
    '關': { s: '關燈。', t: 'Turn off the light.' },
    '多': { s: '多少錢？', t: 'How much money?' },
    '少': { s: '很少。', t: 'Very few.' },
    '冷': { s: '今天很冷。', t: 'It is cold today.' },
    '熱': { s: '今天很熱。', t: 'It is hot today.' },
    '高': { s: '很高興。', t: 'Very happy.' },
    '漂': { s: '漂亮。', t: 'Beautiful.' },
    '亮': { s: '月亮。', t: 'Moon.' },
    '很': { s: '很好。', t: 'Very good.' },
    '太': { s: '太好了。', t: 'That is great.' },
    '都': { s: '我們都是學生。', t: 'We are all students.' },
    '不': { s: '不要。', t: 'Do not want.' },
    '對': { s: '對不起。', t: 'Sorry.' },
    '國': { s: '國家。', t: 'Country.' },
    '北': { s: '北京。', t: 'Beijing.' },
    '京': { s: '南京。', t: 'Nanjing.' },
    '電': { s: '電腦。', t: 'Computer.' },
    '話': { s: '電話。', t: 'Telephone.' },
    '腦': { s: '頭腦。', t: 'Brain.' },
    '視': { s: '電視。', t: 'Television.' },
    '影': { s: '電影。', t: 'Movie.' },
    '院': { s: '醫院。', t: 'Hospital.' },
    '醫': { s: '醫生。', t: 'Doctor.' },
    '店': { s: '書店。', t: 'Bookstore.' },
    '菜': { s: '做菜。', t: 'Cooking.' },
    '錢': { s: '有錢。', t: 'Have money.' },
    '塊': { s: '一塊錢。', t: 'One yuan.' },
    '車': { s: '開車。', t: 'Drive a car.' },
    '場': { s: '操場。', t: 'Playground.' },
    '雨': { s: '下雨。', t: 'Raining.' },
    '東': { s: '東邊。', t: 'East side.' },
    '西': { s: '西瓜。', t: 'Watermelon.' },
    '前': { s: '前面。', t: 'Front.' },
    '後': { s: '後面。', t: 'Back.' },
    '面': { s: '麵條。', t: 'Noodles.' }, // Corrected for meaning context if needed
    '裡': { s: '家裡。', t: 'At home.' },
    '桌': { s: '桌子。', t: 'Table.' },
    '椅': { s: '椅子。', t: 'Chair.' },
    '的': { s: '我的。', t: 'Mine.' },
    '了': { s: '太棒了。', t: 'Awesome.' },
    '嗎': { s: '好嗎？', t: 'Okay?' },
    '吧': { s: '走吧。', t: 'Let\'s go.' },
    '這': { s: '這是什麼？', t: 'What is this?' },
    '那': { s: '那是什麼？', t: 'What is that?' },
    '哪': { s: '哪裡？', t: 'Where?' },
    '怎': { s: '怎麼辦？', t: 'What to do?' },
    '樣': { s: '怎麼樣？', t: 'How is it?' },
    '係': { s: '沒關係。', t: 'It\'s okay.' },
    '正': { s: '正在。', t: 'Currently doing.' },
    '認': { s: '認識。', t: 'To know.' },
    '識': { s: '知識。', t: 'Knowledge.' }
};
